import React, { createContext, useContext, useState, useEffect } from 'react';

// --- Context Types and Setup ---
type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Load language from localStorage if available, otherwise default to Arabic
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('cash-language');
    return (saved === 'ar' || saved === 'en') ? saved : 'ar';
  });
  // Wrap setLanguage to also update localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('cash-language', lang);
  };
  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  useEffect(() => {
    // Apply direction to document
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    // Apply font class based on language
    document.body.className = document.body.className.replace(/font-(arabic|english)/, '');
    document.body.classList.add(language === 'ar' ? 'font-arabic' : 'font-english');
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// --- Translations ---
// (No duplicate keys, grouped by language, and only one set of each key)
const translations = {
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.offers': 'العروض',
    'nav.profile': 'الملف الشخصي',
    'nav.transactions': 'المعاملات',
    'nav.withdrawal': 'السحب',
    'nav.login': 'تسجيل الدخول',
    'nav.admin': 'لوحة الإدارة',
    'nav.logout': 'تسجيل الخروج',
    'nav.deposit': 'الإيداع',
    'nav.help': 'مساعدة',
    'nav.team': 'الفريق',
    'nav.website': 'الموقع',
    'nav.dashboard': 'لوحة التحكم',
    'nav.register': 'تسجيل',
    
    // Login Page
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'ادخل إلى حسابك للوصول لجميع الميزات',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.submit': 'تسجيل الدخول',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.createAccount': 'إنشاء حساب',
    'login.adminLogin': 'دخول المدير',
    'login.userLogin': 'دخول المستخدم',
    'login.success': 'تم تسجيل الدخول بنجاح',
    'login.error': 'خطأ في البريد الإلكتروني أو كلمة المرور',
    'login.unexpectedError': 'حدث خطأ غير متوقع',
    
    // Admin Dashboard
    'admin.title': 'لوحة الإدارة',
    'admin.overview': 'نظرة عامة',
    'admin.users': 'المستخدمون',
    'admin.offers': 'إدارة العروض',
    'admin.withdrawals': 'طلبات السحب',
    'admin.withdrawals.title': 'طلبات السحب',
    'admin.withdrawals.wallet': 'نوع المحفظة',
    'admin.transactions': 'سجل المعاملات',
    'admin.transactions.log': 'سجل شامل لجميع معاملات المنصة متاح للمراجعة والتصدير',
    'admin.notifications': 'الإشعارات',
    'admin.stats.totalUsers': 'إجمالي المستخدمين',
    'admin.stats.pendingVerifications': 'التحققات المعلقة',
    'admin.stats.activeOffers': 'العروض النشطة',
    'admin.stats.pendingWithdrawals': 'السحوبات المعلقة',
    'admin.users.name': 'الاسم',
    'admin.users.email': 'البريد الإلكتروني',
    'admin.users.phone': 'الهاتف',
    'admin.users.status': 'الحالة',
    'admin.users.verified': 'محقق',
    'admin.users.pending': 'معلق',
    'admin.users.actions': 'الإجراءات',
    'admin.users.verify': 'تحقق',
    'admin.users.block': 'حظر',
    'admin.users.view': 'عرض',
    'admin.offers.create': 'إنشاء عرض جديد',
    'admin.offers.title': 'عنوان العرض',
    'admin.offers.description': 'وصف العرض',
    'admin.offers.type': 'نوع العرض',
    'admin.offers.reward': 'المكافأة',
    'admin.offers.cost': 'التكلفة',
    'admin.offers.dailyProfit': 'الربح اليومي',
    'admin.offers.monthlyProfit': 'الربح الشهري',
    'admin.offers.deadline': 'تاريخ الانتهاء',
    'admin.offers.image': 'صورة العرض',
    'admin.offers.clickToUpload': 'انقر للرفع',
    'admin.offers.orDragDrop': 'أو اسحب وأفلت',
    'admin.offers.imageFormats': 'PNG, JPG, GIF حتى 10 ميجابايت',
    'admin.offers.edit': 'تعديل',
    'admin.offers.delete': 'حذف',
    'admin.withdrawals.user': 'المستخدم',
    'admin.withdrawals.amount': 'المبلغ',
    'admin.withdrawals.type': 'النوع',
    'admin.withdrawals.method': 'الطريقة',
    'admin.withdrawals.date': 'التاريخ',
    'admin.withdrawals.approve': 'موافقة',
    'admin.withdrawals.reject': 'رفض',
    'admin.notifications.send': 'إرسال إشعار',
    'admin.notifications.title': 'عنوان الإشعار',
    'admin.notifications.message': 'الرسالة',
    'admin.notifications.type': 'نوع الإشعار',
    'admin.notifications.type.info': 'معلومات',
    'admin.notifications.type.offer': 'عرض',
    'admin.notifications.type.ad': 'إعلان',
    'admin.notifications.type.warning': 'تحذير',
    'admin.notifications.type.success': 'نجاح',
    'admin.notifications.type.error': 'خطأ',
    'admin.notifications.target': 'المستهدف',
    'admin.notifications.target.all': 'الجميع',
    'admin.notifications.target.user': 'مستخدم محدد',
    'admin.notifications.target.placeholder': 'أدخل معرف المستخدم',
    'admin.notifications.banner': 'إشعار بانر',
    'admin.notifications.schedule': 'جدولة الإشعار',
    'admin.notifications.scheduledAt': 'مجدول في',
    'admin.notifications.image': 'صورة',
    'admin.notifications.status': 'الحالة',
    'admin.notifications.status.sent': 'تم الإرسال',
    'admin.notifications.status.scheduled': 'مجدول',
    'admin.notifications.actions': 'الإجراءات',
    'admin.notifications.noNotifications': 'لا توجد إشعارات',
    'admin.notifications.sendToAll': 'إرسال للجميع',
    'admin.export.users': 'تصدير المستخدمين',
    'admin.export.transactions': 'تصدير المعاملات',
    'admin.export.title': 'تصدير البيانات',
    'admin.export.type': 'نوع البيانات',
    'admin.export.format': 'صيغة التصدير',
    'admin.export.selectFormat': 'اختر الصيغة',
    'admin.export.export': 'تصدير',
    'admin.export.exporting': 'جاري التصدير...',
    'admin.export.success': 'تم التصدير بنجاح',
    'admin.export.error': 'حدث خطأ أثناء التصدير',
    'admin.export.pdfSuccess': 'تم إنشاء ملف PDF بنجاح',
    'admin.export.pdfReady': 'تم فتح نافذة الطباعة لتصدير PDF',
    'admin.export.excelSuccess': 'تم تصدير ملف Excel بنجاح',
    'admin.export.excelReady': 'تم تحميل ملف Excel بنجاح',
    'admin.chat': 'الدعم المباشر',
    'admin.supportChat': 'دعم العملاء',
    'admin.chat.searchConversations': 'البحث في المحادثات...',
    'admin.chat.selectConversation': 'اختر محادثة لعرض الرسائل',
    
    // Home Page
    'home.title': 'مرحباً بك في كاش',
    'home.subtitle': 'منصة التداول الذكية لإدارة أرباحك بأمان',
    'home.cta': 'ابدأ الآن',
    'home.cta2.title': 'ابدأ رحلتك مع كاش اليوم',
    'home.cta2.subtitle': 'انضم إلى آلاف المستخدمين الذين يثقون بمنصة كاش لإدارة أرباحهم',
    'home.cta2.button': 'إنشاء حساب مجاني',
    
    // Features
    'features.secure': 'آمن ومضمون',
    'features.secure.desc': 'نحن نستخدم أحدث تقنيات الأمان لحماية أموالك',
    'features.fast': 'سريع وموثوق',
    'features.fast.desc': 'معاملات سريعة ونظام موثوق لإدارة أرباحك',
    'features.support': 'دعم 24/7',
    'features.support.desc': 'فريق الدعم متوفر طوال الوقت لمساعدتك',
    
    // Offers Page
    'offers.title': 'العروض المتاحة',
    'offers.subtitle': 'اكتشف العروض المتاحة واحصل على مكافآت إضافية',
    'offers.trading': 'تداول',
    'offers.referral': 'إحالة',
    'offers.premium': 'متقدم',
    'offers.deadline': 'تاريخ الانتهاء:',
    'offers.minAmount': 'الحد الأدنى:',
    'offers.join': 'الانضمام للعرض',
    'offers.notification.title': 'لا تفوت العروض الجديدة!',
    'offers.notification.subtitle': 'اشترك في الإشعارات للحصول على آخر العروض والمكافآت',
    'offers.notification.button': 'اشترك في الإشعارات',
    
    // Profile Page
    'profile.totalEarnings': 'إجمالي الأرباح',
    'profile.recentActivity': 'النشاط الأخير',
    'profile.accountStatus': 'حالة الحساب',
    'profile.emailVerification': 'التحقق من البريد الإلكتروني',
    'profile.phoneVerification': 'التحقق من الهاتف',
    'profile.identityVerification': 'التحقق من الهوية',
    'profile.accountLevel': 'مستوى الحساب',
    'profile.withdrawalStatus': 'حالة السحب',
    'profile.withdrawalEligible': 'حسابك مؤهل لجميع عمليات السحب',
    'profile.verified': 'تم التحقق',
    'profile.pending': 'في انتظار التحقق',
    'profile.completed': 'مكتمل',
    'profile.advanced': 'متقدم',
    'profile.memberSince': 'عضو منذ:',
    'profile.updateAccountInfo': 'تحديث بيانات الحساب',
    'profile.firstName': 'الاسم الأول',
    'profile.firstNamePlaceholder': 'أدخل الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.lastNamePlaceholder': 'أدخل اسم العائلة',
    'profile.phone': 'رقم الهاتف',
    'profile.phonePlaceholder': 'أدخل رقم الهاتف',
    'profile.wallet': 'المحفظة الإلكترونية',
    'profile.selectWallet': 'اختر المحفظة',
    'profile.walletVodafone': 'فودافون كاش',
    'profile.walletOrange': 'أورنج كاش',
    'profile.walletWePay': 'وي باي',
    'profile.walletEtisalat': 'اتصالات كاش',
    'profile.idFront': 'صورة الهوية - الوجه الأمامي',
    'profile.idBack': 'صورة الهوية - الوجه الخلفي',
    'profile.saving': 'جاري الحفظ...',
    'profile.save': 'حفظ البيانات',
    
    // Transactions Page
    'transactions.title': 'سجل المعاملات',
    'transactions.subtitle': 'تتبع جميع معاملاتك المالية',
    'transactions.search': 'البحث في المعاملات...',
    'transactions.all': 'جميع المعاملات',
    'transactions.withdrawal': 'سحب',
    'transactions.deposit': 'إيداع',
    'transactions.bonus': 'مكافأة',
    'transactions.earning': 'أرباح',
    'transactions.completed': 'مكتمل',
    'transactions.approved': 'تمت الموافقة',
    'transactions.pending': 'قيد المعالجة',
    'transactions.rejected': 'مرفوض',
    'transactions.id': 'معرف المعاملة:',
    'transactions.noResults': 'لا توجد معاملات مطابقة',
    'transactions.summary': 'ملخص المعاملات',
    'transactions.totalIncome': 'إجمالي الإيرادات',
    'transactions.totalWithdrawals': 'إجمالي السحوبات',
    'transactions.pendingCount': 'معاملات قيد المعالجة',
    
    // Withdrawal Page
    'withdrawal.title': 'طلب سحب',
    'withdrawal.subtitle': 'اطلب سحب أرباحك بأمان وسهولة',
    'withdrawal.newRequest': 'طلب سحب جديد',
    'withdrawal.type': 'نوع السحب',
    'withdrawal.amount': 'المبلغ',
    'withdrawal.method': 'طريقة السحب',
    'withdrawal.accountDetails': 'تفاصيل الحساب',
    'withdrawal.maxAmount': 'الحد الأقصى:',
    'withdrawal.selectType': 'اختر نوع السحب',
    'withdrawal.selectMethod': 'اختر طريقة السحب',
    'withdrawal.accountPlaceholder': 'رقم الحساب أو عنوان المحفظة',
    'withdrawal.submit': 'تقديم طلب السحب',
    'withdrawal.warning': 'سيتم مراجعة طلب السحب خلال 24-48 ساعة. تأكد من صحة تفاصيل الحساب.',
    'withdrawal.balances': 'الأرصدة المتاحة',
    'withdrawal.verificationStatus': 'حالة التحقق',
    'withdrawal.eligible': 'حسابك مؤهل لجميع عمليات السحب',
    'withdrawal.verificationRequired': 'التحقق مطلوب',
    'withdrawal.verificationMessage': 'يجب إكمال التحقق من الهوية قبل تقديم طلبات السحب',
    'withdrawal.completeVerification': 'إكمال التحقق',
    'withdrawal.bank': 'التحويل البنكي',
    'withdrawal.wallet': 'المحفظة الإلكترونية',
    'withdrawal.crypto': 'العملة المشفرة',
    'withdrawal.error.verification': 'خطأ في التحقق',
    'withdrawal.error.verificationMessage': 'يجب إكمال التحقق من الهوية قبل طلب السحب',
    'withdrawal.error.amount': 'خطأ في المبلغ',
    'withdrawal.error.amountMessage': 'المبلغ المطلوب أكبر من الرصيد المتاح',
    'withdrawal.success.message': 'تم إرسال طلب السحب بنجاح وسيتم مراجعته قريباً',
    'withdrawal.error.timeSlot': 'خطأ في وقت السحب',
    'withdrawal.error.timeSlotMessage': 'السحوبات مسموحة فقط خلال الأوقات المحددة من قبل الإدارة',
    'withdrawal.error.limit': 'خطأ في الحد',
    'withdrawal.error.minAmount': 'المبلغ أقل من الحد الأدنى المطلوب (${min})',
    'withdrawal.error.maxAmount': 'المبلغ أكبر من الحد الأقصى المسموح (${max})',
    'withdrawal.error.dailyLimit': 'تجاوز الحد اليومي. الحد اليومي: ${daily}، المستخدم: ${used}، المتبقي: ${remaining}',
    'withdrawal.error.loadData': 'فشل في تحميل بيانات السحب',
    'withdrawal.history': 'سجل السحوبات',
    'withdrawal.noHistory': 'لا توجد سحوبات سابقة',
    'withdrawal.history.id': 'رقم الطلب',
    'withdrawal.history.type': 'النوع',
    'withdrawal.history.amount': 'المبلغ',
    'withdrawal.history.method': 'الطريقة',
    'withdrawal.history.status': 'الحالة',
    'withdrawal.history.date': 'التاريخ',
    'withdrawal.history.details': 'التفاصيل',
    'withdrawal.status.pending': 'قيد المعالجة',
    'withdrawal.status.approved': 'تمت الموافقة',
    'withdrawal.status.rejected': 'مرفوض',
    'withdrawal.status.paid': 'تم الدفع',
    'withdrawal.rejectionReason': 'سبب الرفض',
    'withdrawal.adminNote': 'ملاحظة المدير',
    'withdrawal.packageLimits': 'حدود الحزمة: الحد الأدنى ${min}، الحد الأقصى ${max}، الحد اليومي ${daily}',
    'withdrawal.noDetails': 'لا توجد تفاصيل إضافية',
    
    // Registration
    'register.title': 'إنشاء حساب جديد',
    'register.displayName': 'اسم العرض',
    'register.firstName': 'الاسم الأول',
    'register.lastName': 'اسم العائلة',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.password': 'كلمة المرور',
    'register.referralCode': 'كود الإحالة (اختياري)',
    'register.referredBy': 'تم الإحالة بواسطة',
    'register.checkingReferral': 'جاري التحقق من كود الإحالة...',
    'register.error.invalidReferral': 'يرجى إدخال كود إحالة صحيح',
    'register.idFront': 'صورة الهوية - الوجه الأمامي',
    'register.idBack': 'صورة الهوية - الوجه الخلفي',
    'register.submit': 'إنشاء الحساب',
    'register.hasAccount': 'هل لديك حساب بالفعل؟',
    'register.login': 'تسجيل الدخول',
    'register.required': 'جميع الحقول مطلوبة',
    'register.success': 'تم إرسال طلب التسجيل بنجاح',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    
    // Theme
    'theme.light': 'الوضع الفاتح',
    'theme.dark': 'الوضع الداكن',
    'language.switch': 'English',
    
    // Deposit Feature
    'deposit.title': 'إيداع الأموال',
    'deposit.subtitle': 'أرسل الأموال إلى أحد الأرقام الرسمية وأرفق صورة التحويل',
    'deposit.amount': 'المبلغ',
    'deposit.userNumber': 'رقمك المستخدم للإرسال',
    'deposit.targetNumber': 'رقم الإيداع الرسمي',
    'deposit.upload': 'رفع صورة التحويل',
    'deposit.submit': 'إرسال طلب الإيداع',
    'deposit.success': 'تم إرسال طلب الإيداع بنجاح وسيتم مراجعته قريباً',
    'deposit.error.maxNumbers': 'لا يمكن إضافة أكثر من 10 أرقام إيداع',
    'deposit.error.required': 'جميع الحقول مطلوبة',
    'deposit.error.imageType': 'يجب أن تكون الصورة من نوع jpg أو png',
    'deposit.status.pending': 'قيد المراجعة',
    'deposit.status.approved': 'تمت الموافقة',
    'deposit.status.rejected': 'مرفوض',
    'deposit.numbers': 'أرقام الإيداع الرسمية',
    'deposit.requests': 'طلبات الإيداع',
    'deposit.history': 'سجل الإيداعات',
    'deposit.screenshot': 'صورة التحويل',
    'deposit.status': 'الحالة',
    'deposit.actions': 'الإجراءات',
    'deposit.view': 'عرض',
    'deposit.date': 'التاريخ',
    'deposit.approve': 'موافقة',
    'deposit.reject': 'رفض',
    'deposit.user': 'المستخدم',
    
    // Help Center
    'help.title': 'مركز المساعدة',
    'help.subtitle': 'دليل شامل لجميع الخدمات والميزات',
    'help.deposit.title': 'كيفية الإيداع',
    'help.deposit.step1': '1. اختر أحد الأرقام الرسمية للإيداع',
    'help.deposit.step2': '2. أرسل المبلغ المطلوب إلى الرقم المختار',
    'help.deposit.step3': '3. التقط صورة للتحويل أو الإيصال',
    'help.deposit.step4': '4. املأ النموذج وأرفق الصورة',
    'help.deposit.step5': '5. انتظر مراجعة الطلب (24-48 ساعة)',
    'help.withdrawal.title': 'كيفية السحب',
    'help.withdrawal.step1': '1. تأكد من إكمال التحقق من الهوية',
    'help.withdrawal.step2': '2. اختر نوع السحب والمبلغ',
    'help.withdrawal.step3': '3. أدخل تفاصيل الحساب أو المحفظة',
    'help.withdrawal.step4': '4. راجع المعلومات وتأكد من صحتها',
    'help.withdrawal.step5': '5. أرسل الطلب وانتظر المراجعة',
    'help.invite.title': 'كيفية دعوة الآخرين',
    'help.invite.step1': '1. اذهب إلى صفحة العروض',
    'help.invite.step2': '2. اختر عرض الإحالة',
    'help.invite.step3': '3. انسخ رابط الإحالة الخاص بك',
    'help.invite.step4': '4. شارك الرابط مع أصدقائك',
    'help.invite.step5': '5. احصل على مكافآت عند انضمامهم',
    'help.packages.title': 'كيفية عمل الحزم',
    'help.packages.step1': '1. تصفح الحزم المتاحة في صفحة العروض',
    'help.packages.step2': '2. اختر الحزمة المناسبة لميزانيتك',
    'help.packages.step3': '3. اقرأ الشروط والأحكام بعناية',
    'help.packages.step4': '4. ادفع المبلغ المطلوب',
    'help.packages.step5': '5. ابدأ في كسب الأرباح حسب الشروط',
    'help.faq.title': 'الأسئلة الشائعة',
    'help.faq.q1': 'كم تستغرق مراجعة طلب الإيداع؟',
    'help.faq.a1': 'تستغرق مراجعة طلب الإيداع عادة 24-48 ساعة عمل.',
    'help.faq.q2': 'ما هي الحد الأدنى للسحب؟',
    'help.faq.a2': 'الحد الأدنى للسحب يختلف حسب نوع الحساب والحزمة.',
    'help.faq.q3': 'كيف يمكنني التحقق من حالة طلبي؟',
    'help.faq.a3': 'يمكنك تتبع حالة طلبك في صفحة المعاملات.',
    'help.faq.q4': 'هل يمكنني إلغاء طلب السحب؟',
    'help.faq.a4': 'لا يمكن إلغاء طلب السحب بعد إرساله، لذا تأكد من صحة المعلومات.',
    'help.faq.q5': 'كيف أحصل على مكافآت الإحالة؟',
    'help.faq.a5': 'تحصل على مكافآت الإحالة عند انضمام أصدقائك عبر رابطك.',
    'help.faq.q6': 'ما هي طرق الدفع المقبولة؟',
    'help.faq.a6': 'نقبل جميع المحافظ الإلكترونية الرئيسية في مصر.',
    
    // Chat Support
    'chat.title': 'الدعم المباشر',
    'chat.subtitle': 'تواصل مع فريق الدعم للحصول على المساعدة',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.send': 'إرسال',
    'chat.typing': 'جاري الكتابة...',
    'chat.online': 'متصل',
    'chat.offline': 'غير متصل',
    'chat.agent': 'ممثل الدعم',
    'chat.user': 'أنت',
    'chat.welcome': 'مرحباً! كيف يمكنني مساعدتك اليوم؟',
    'chat.quickReplies': 'ردود سريعة',
    'chat.quickReply.deposit': 'مشكلة في الإيداع',
    'chat.quickReply.withdrawal': 'مشكلة في السحب',
    'chat.quickReply.account': 'مشكلة في الحساب',
    'chat.quickReply.technical': 'مشكلة تقنية',
    'chat.quickReply.other': 'أخرى',
    'chat.status.connected': 'متصل',
    'chat.status.connecting': 'جاري الاتصال...',
    'chat.status.disconnected': 'غير متصل',
    'chat.error.connection': 'خطأ في الاتصال',
    'chat.error.message': 'فشل في إرسال الرسالة',
    'chat.minimize': 'تصغير',
    'chat.maximize': 'تكبير',
    'chat.close': 'إغلاق',
    'chat.newMessage': 'رسالة جديدة',
    'chat.noMessages': 'لا توجد رسائل بعد',
    'chat.loading': 'جاري التحميل...',
    'chat.attachment': 'إرفاق ملف',
    'chat.attachment.error': 'خطأ في رفع الملف',
    'chat.attachment.size': 'حجم الملف كبير جداً',
    'chat.attachment.type': 'نوع الملف غير مدعوم',

    // Home Page Hero Section
    'home.hero.title': 'مرحباً بك في كاش',
    'home.hero.subtitle': 'منصة التداول الذكية لإدارة أرباحك بأمان',
    'home.hero.cta': 'ابدأ الآن',
    'home.hero.learnMore': 'اعرف المزيد',

    // Home Page Features Section
    'home.features.title': 'لماذا تختار كاش؟',

    // Home Page CTA Section
    'home.cta.title': 'ابدأ رحلتك مع كاش اليوم',
    'home.cta.subtitle': 'انضم إلى آلاف المستخدمين الذين يثقون بمنصة كاش لإدارة أرباحهم',
    'home.cta.button': 'إنشاء حساب مجاني',  
    
    // Admin Dashboard Additional
    'admin.analytics': 'التحليلات',
    'admin.analytics.newUsersOverTime': 'المستخدمون الجدد عبر الزمن',
    'admin.analytics.transactionTypes': 'أنواع المعاملات',
    'admin.analytics.activityByHour': 'النشاط حسب الساعة',
    'admin.analytics.newUsers': 'المستخدمون الجدد',
    'admin.analytics.date': 'التاريخ',
    'admin.analytics.count': 'العدد',
    'admin.analytics.activity': 'النشاط',
    'admin.analytics.hour': 'الساعة',
    'admin.analytics.chartPlaceholder': 'سيتم إضافة الرسوم البيانية قريباً',
    'admin.analytics.approved': 'تمت الموافقة',
    'admin.analytics.pending': 'قيد المعالجة',
    'admin.analytics.rejected': 'مرفوض',
    'admin.analytics.noData': 'لا توجد بيانات متاحة',
    'admin.loading': 'جاري التحميل...',
    'admin.noUsers': 'لا يوجد مستخدمون',
    'admin.view': 'عرض',
    'admin.verify': 'تحقق',
    'admin.remove': 'حذف',
    'admin.manageOffers': 'إدارة العروض',
    'admin.usersCount': 'المستخدمون:',
    'admin.profitLoss': 'الربح/الخسارة:',
    'admin.proof': 'إثبات',
    'admin.confirmPay': 'تأكيد الدفع',
    'admin.rejectTitle': 'رفض الطلب',
    'admin.adminNote': 'ملاحظة المدير',
    'admin.proofImage': 'صورة الإثبات',
    'admin.rejectionReason': 'سبب الرفض',
    'admin.settings': 'الإعدادات',
    'admin.timeSlots': 'فترات السحب',
    'admin.saveTimeSlots': 'حفظ فترات السحب',
    'admin.packageLimits': 'حدود الحزم',
    'admin.savePackageLimits': 'حفظ حدود الحزم',
    'admin.monthlyDeposits': 'إجمالي الإيداعات هذا الشهر',
    'admin.withdrawals.pay': 'دفع',
    'admin.withdrawals.requests': 'طلبات',
    'admin.withdrawals.noRequests': 'لا توجد طلبات سحب',
    'admin.withdrawalSettings': 'إعدادات السحب',
    'admin.timeSlotsDescription': 'حدد الأوقات المسموحة للسحب (اليوم:الساعة:الدقيقة)',
    'admin.addTimeSlot': 'إضافة وقت',
    'admin.packageLimitsDescription': 'حدد حدود السحب لكل حزمة',
    'admin.package': 'حزمة',
    'admin.minAmount': 'الحد الأدنى',
    'admin.maxAmount': 'الحد الأقصى',
    'admin.dailyLimit': 'الحد اليومي',
    'admin.adminNotePlaceholder': 'أضف ملاحظة للمستخدم (اختياري)',
    'admin.clickToUploadProof': 'انقر لرفع صورة الإثبات',
    'admin.rejectionReasonPlaceholder': 'اذكر سبب رفض الطلب',
    'admin.rejectionReasonHelp': 'سيتم إرسال هذا السبب للمستخدم',
    'admin.withdrawals.paymentConfirmed': 'تم تأكيد الدفع بنجاح',
    'admin.withdrawals.paymentFailed': 'فشل في تأكيد الدفع',
    'admin.withdrawals.rejectionConfirmed': 'تم رفض الطلب بنجاح',
    'admin.withdrawals.rejectionFailed': 'فشل في رفض الطلب',
    'admin.weeklyNewUsers': 'المستخدمون الجدد هذا الأسبوع',
    'admin.avgTransactionValue': 'متوسط قيمة المعاملة',
    'admin.searchPlaceholder': 'البحث بالاسم أو البريد الإلكتروني أو الهاتف...',
    'admin.verificationStatus': 'حالة التحقق',
    'admin.allStatuses': 'جميع الحالات',
    'admin.verified': 'محقق',
    'admin.pending': 'معلق',
    'admin.registrationDate': 'تاريخ التسجيل',
    'admin.exportUsers': 'تصدير المستخدمين',
    'admin.exportTransactions': 'تصدير المعاملات',
    'admin.failedToFetch': 'فشل في جلب البيانات',
    'admin.failedToFetchReferrers': 'فشل في جلب أفضل المحيلين',
    'admin.failedToUpdateSettings': 'فشل في تحديث الإعدادات',
    'admin.settingsUpdated': 'تم تحديث الإعدادات بنجاح',
    'admin.referralSettings': 'إعدادات نظام الإحالة',
    'admin.level1Points': 'نقاط المستوى الأول (الإحالات المباشرة)',
    'admin.level2Points': 'نقاط المستوى الثاني (الإحالات غير المباشرة)',
    'admin.level3Points': 'نقاط المستوى الثالث',
    'admin.updateSettings': 'تحديث الإعدادات',
    'admin.topReferrers': 'أفضل المحيلين',
    'admin.noReferrers': 'لا يوجد محيلون',
    'admin.referralStats': 'إحصائيات الإحالة',
    'admin.totalReferrals': 'إجمالي الإحالات',
    'admin.totalPointsAwarded': 'إجمالي النقاط الممنوحة',
    'admin.activeReferrers': 'المحيلون النشطون',
    'admin.pts': 'نقاط',
    'admin.referrals': 'إحالات',
    'admin.userVerified': 'تم التحقق من المستخدم بنجاح',
    'admin.userRemoved': 'تم حذف المستخدم بنجاح',
    'admin.clearFilters': 'مسح الفلاتر',
    'admin.activeFilters': 'الفلاتر النشطة',
    'admin.noResults': 'لا توجد نتائج',
    'admin.refresh': 'تحديث',
    'admin.details': 'التفاصيل',
    'admin.summary': 'الملخص',
    'admin.dashboard': 'لوحة التحكم',
    'admin.confirm': 'تأكيد',
    'admin.back': 'رجوع',
    'admin.next': 'التالي',
    'admin.previous': 'السابق',
    'admin.first': 'الأول',
    'admin.last': 'الأخير',
    'admin.page': 'صفحة',
    'admin.of': 'من',
    'admin.items': 'عناصر',
    'admin.perPage': 'لكل صفحة',
    'admin.showing': 'عرض',
    'admin.to': 'إلى',
    'admin.entries': 'إدخالات',
    
    // Quick Actions
    'admin.quickActions': 'الإجراءات السريعة',
    'admin.quickActions.manageOffers': 'إدارة العروض',
    'admin.quickActions.exportUsers': 'تصدير المستخدمين',
    'admin.quickActions.exportData': 'تصدير البيانات',
    'admin.quickActions.sendNotification': 'إرسال إشعار',
    'admin.quickActions.addDepositNumber': 'إضافة رقم إيداع',
    'admin.quickActions.manageReferrals': 'إدارة الإحالات',
    'admin.quickActions.viewAnalytics': 'عرض التحليلات',
    'admin.quickActions.manageWithdrawals': 'إدارة السحوبات',
    'admin.quickActions.supportChat': 'دعم العملاء',
    
    // Offers
    'offers.manageOffers': 'إدارة العروض',
    'offers.saving': 'جاري الحفظ...',
    'offers.update': 'تحديث',
    'offers.create': 'إنشاء',
    'offers.preview': 'معاينة',
    'offers.removePreview': 'إزالة المعاينة',
    
    // Deposit
    'deposit.loading': 'جاري تحميل صفحة الإيداع...',
    'deposit.loadingNumber': 'جاري تحميل رقم الإيداع...',
    'deposit.loginRequired': 'يرجى تسجيل الدخول للوصول لصفحة الإيداع',
    'deposit.noNumbersAvailable': 'لا توجد أرقام إيداع متاحة',
    'deposit.acceptedFormats': 'الصيغ المقبولة: JPEG, PNG. الحد الأقصى: 5 ميجابايت',
    'deposit.submitting': 'جاري الإرسال...',
    'deposit.error.unexpected': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    
    // Common Additional
    'common.required': 'مطلوب',
    'common.close': 'إغلاق',
    'common.userDetails': 'تفاصيل المستخدم',
    'common.name': 'الاسم:',
    'common.email': 'البريد الإلكتروني:',
    'common.phone': 'الهاتف:',
    'common.wallet': 'المحفظة:',
    'common.verified': 'محقق:',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.now': 'الآن',
    'common.minutes': 'د',
    'common.hours': 'س',
    'common.days': 'يوم',

    // NotFound Page
    'notfound.404': '٤٠٤',
    'notfound.oops': 'عذراً! الصفحة غير موجودة',
    'notfound.returnHome': 'العودة للرئيسية',

    // ReferralCode Component
    'referral.program': 'برنامج الإحالة',
    'referral.accountVerificationRequired': 'مطلوب التحقق من الحساب',
    'referral.verifyToAccess': 'يرجى التحقق من حسابك للوصول إلى برنامج الإحالة وكسب المكافآت.',
    'referral.loading': 'جاري تحميل بيانات الإحالة...',
    'referral.yourProgram': 'برنامج الإحالة الخاص بك',
    'referral.yourCode': 'كود الإحالة الخاص بك',
    'referral.totalReferrals': 'إجمالي الإحالات',
    'referral.pointsEarned': 'النقاط المكتسبة',
    'referral.level1': 'المستوى 1',
    'referral.level2plus3': 'المستوى 2+3',
    'referral.howItWorks': 'كيف يعمل',
    'referral.howItWorks.level1': 'اكسب نقاط عند تسجيل أصدقائك باستخدام كودك',
    'referral.howItWorks.level2': 'اكسب نقاط عند إحالة أصدقائك للآخرين',
    'referral.howItWorks.level3': 'اكسب نقاط من الإحالات من المستوى الثالث',
    'referral.howItWorks.share': 'شارك كودك مع أصدقائك لبدء كسب المكافآت!',

    // Transactions/General
    'transactions.paymentProcessed': 'تمت معالجة الدفع بنجاح',
    'transactions.invalidBankDetails': 'تم إدخال تفاصيل حساب بنكي غير صحيحة',
    'transactions.friendReferralBonus': 'مكافأة إحالة صديق',
    'transactions.personalEarningsWithdrawal': 'سحب أرباح شخصية',
    'transactions.teamEarningsWithdrawal': 'سحب أرباح فريق',
    'transactions.capitalDeposit': 'إيداع رأس مال',
    'transactions.bank': 'بنك',
    'transactions.wallet': 'محفظة',
    'transactions.bankTransfer': 'تحويل بنكي',
    'transactions.cryptocurrency': 'عملة مشفرة',
    'transactions.teamEarnings': 'أرباح الفريق',
    'common.completeProfile': 'يرجى إكمال بيانات حسابك للوصول للموقع. سيتم تحويلك لإعداد الحساب...',
    'deposit.completeProfile': 'يرجى إكمال بيانات حسابك لإجراء الإيداعات. سيتم تحويلك لإعداد الحساب...',
    // Help Center Additional
    'help.needMoreHelp': 'تحتاج مساعدة إضافية؟',
    'help.supportMessage': 'فريق الدعم متوفر على مدار الساعة لمساعدتك في أي استفسارات أو مخاوف.',
    'help.emailSupport': 'الدعم عبر البريد الإلكتروني',
    'help.liveChat': 'الدردشة المباشرة',
    // Offers Additional
    'offers.joined': 'تم الانضمام',
    'offers.cost': 'التكلفة:',
    'offers.dailyProfit': 'الربح اليومي:',
    'offers.monthlyProfit': 'الربح الشهري:',
    'offers.notifyMe': 'أبلغني',
    'offers.stayTuned': 'تابع آخر العروض والمكافآت.',
    // Transactions Descriptions/Methods
    'transactions.desc.personalEarningsWithdrawal': 'سحب أرباح شخصية',
    'transactions.desc.friendReferralBonus': 'مكافأة إحالة صديق',
    'transactions.desc.teamEarnings': 'أرباح الفريق',
    'transactions.desc.bonusWithdrawal': 'سحب مكافآت',
    'transactions.desc.capitalDeposit': 'إيداع رأس مال',
    'transactions.desc.teamEarningsWithdrawal': 'سحب أرباح فريق',
    'transactions.method.bank': 'بنك',
    'transactions.method.wallet': 'محفظة',
    'transactions.method.bankTransfer': 'تحويل بنكي',
    'transactions.method.cryptocurrency': 'عملة مشفرة',
    'transactions.approvedForProcessing': 'تمت الموافقة للمعالجة',
    // Register Page Additional
    'register.invalidReferralTitle': 'كود الإحالة غير صالح',
    'register.invalidReferralDesc': 'كود الإحالة الذي أدخلته غير صالح.',
    'register.unverifiedReferralDesc': 'كود الإحالة يخص حساب غير موثق.',
    'register.validReferralTitle': 'كود الإحالة صالح',
    'register.validReferralDesc': 'سيتم إحالتك بواسطة',
    // Profile Page Additional
    'profile.noData': 'لا توجد بيانات للملف الشخصي',
    'profile.noDataDesc': 'يرجى إكمال بيانات حسابك لعرض ملفك الشخصي.',
    'profile.updateAccount': 'تحديث بيانات الحساب',
    'profile.achievements': 'الإنجازات',
    'profile.level': 'المستوى',
    'profile.levelDesc': 'مستواك الحالي',
    'profile.badges': 'الشارات',
    'profile.noBadges': 'لم تحصل على أي شارات بعد',
    'profile.accountInfo': 'معلومات الحساب',
    'profile.edit': 'تعديل',
    'profile.idPhotos': 'صور الهوية',
    'profile.profilePhoto': 'صورة الملف الشخصي',
    'profile.view': 'عرض',
    'profile.idFrontLabel': 'الوجه الأمامي',
    'profile.idBackLabel': 'الوجه الخلفي',
    'profile.balance': 'الرصيد الحالي',
    'profile.personalEarnings': 'الأرباح الشخصية',
    'profile.teamEarnings': 'أرباح الفريق',
    'profile.bonuses': 'المكافآت',
    'profile.capital': 'رأس المال',
    // ... existing code ...
    'admin.accept': 'قبول',
    'admin.reject': 'رفض',
    'admin.gamification': 'التلعيب',
    'admin.gamificationSettings': 'إعدادات التلعيب',
    'admin.pointsMultiplier': 'مضاعف النقاط',
    'admin.automation': 'الأتمتة',
    'admin.badges': 'الشارات',
    'admin.createBadge': 'إنشاء شارة',
    'admin.editBadge': 'تعديل الشارة',
    'admin.badgeName': 'اسم الشارة',
    'admin.badgeDescription': 'وصف الشارة',
    'admin.badgeType': 'نوع الشارة',
    'admin.badgeRequirement': 'متطلب الشارة',
    'admin.badgePoints': 'نقاط الشارة',
    'admin.badgeActive': 'الشارة نشطة',
    'admin.update': 'تحديث',
    'admin.create': 'إنشاء',
    'admin.noBadges': 'لا توجد شارات',
    'admin.levels': 'المستويات',
    'admin.createLevel': 'إنشاء مستوى',
    'admin.editLevel': 'تعديل المستوى',
    'admin.levelNumber': 'رقم المستوى',
    'admin.levelRequirement': 'النقاط المطلوبة',
    'admin.levelName': 'اسم المستوى',
    'admin.levelDescription': 'وصف المستوى',
    'admin.levelBenefits': 'مزايا المستوى',
    'admin.noLevels': 'لا توجد مستويات',
    'admin.userBadges': 'شارات المستخدم',
    'admin.assignBadge': 'تعيين شارة',
    'admin.editUserBadge': 'تعديل شارة المستخدم',
    'admin.pointsEarned': 'النقاط المكتسبة',
    'admin.assign': 'تعيين',
    'admin.noUserBadges': 'لا توجد شارات للمستخدم',
    'admin.confirmDelete': 'تأكيد الحذف',
    'admin.deleteWarning': 'هل أنت متأكد أنك تريد الحذف',
    'admin.deleteWarning2': 'هذا الإجراء لا يمكن التراجع عنه.',
    'admin.badgeType.achievement': 'إنجاز',
    'admin.badgeType.referral': 'إحالة',
    'admin.badgeType.deposit': 'إيداع',
    'admin.badgeType.withdrawal': 'سحب',
    'admin.badgeType.profile': 'الملف الشخصي',
    'admin.badgeType.verification': 'التحقق',
    'admin.badgeType.special': 'خاص',
    'admin.badgeType.loyalty': 'ولاء',
    'admin.automation.enabled': 'مفعل',
    'admin.automation.disabled': 'معطل',
    'admin.placeholder.badgeName': 'أدخل اسم الشارة',
    'admin.placeholder.badgeDescription': 'أدخل وصف الشارة',
    'admin.placeholder.levelName': 'أدخل اسم المستوى',
    'admin.placeholder.levelDescription': 'أدخل وصف المستوى',
    'admin.placeholder.levelBenefits': 'أدخل مزايا المستوى',
    'admin.placeholder.packageName': 'اسم الحزمة',
    'admin.placeholder.min': 'الحد الأدنى',
    'admin.placeholder.max': 'الحد الأقصى',
    'admin.placeholder.daily': 'اليومي',
    'admin.placeholder.startHour': 'ساعة البدء',
    'admin.placeholder.mobileNumber': 'رقم الجوال',
    'admin.placeholder.selectUser': 'اختر المستخدم',
    'admin.placeholder.selectBadge': 'اختر الشارة',
    'admin.placeholder.noneSet': 'لم يتم التعيين',
    'admin.current': 'الحالي',
    'admin.enabled': 'مفعل',
    'admin.disabled': 'معطل',
    'admin.req': 'مطلوب',
    'admin.actions': 'الإجراءات',
    'admin.user': 'المستخدم',
    'admin.badge': 'شارة',
    'admin.earnedAt': 'تاريخ الحصول',
    'admin.points': 'النقاط',
    'admin.benefits': 'المزايا',
    'admin.description': 'الوصف',
    'admin.type': 'النوع',
    'admin.requirement': 'المتطلب',
    'admin.pointsAwarded': 'النقاط الممنوحة',
    'admin.active': 'نشط',
    'admin.cancel': 'إلغاء',
    'admin.save': 'حفظ',
    'admin.close': 'إغلاق',
    'admin.add': 'إضافة',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.day': 'اليوم',
    'common.day.sunday': 'الأحد',
    'common.day.monday': 'الاثنين',
    'common.day.tuesday': 'الثلاثاء',
    'common.day.wednesday': 'الأربعاء',
    'common.day.thursday': 'الخميس',
    'common.day.friday': 'الجمعة',
    'common.day.saturday': 'السبت',
    'language.arabic': 'عربي',
    'language.english': 'EN',
    'common.active': 'نشط',
    'common.actions': 'الإجراءات',
    'offers.image': 'صورة',
    'offers.description': 'الوصف',
    'offers.amount': 'المبلغ',
    'offers.noDeadline': 'لا يوجد موعد نهائي',
    'common.day': 'اليوم',
    'common.startHour': 'ساعة البدء',
    'common.endHour': 'ساعة الانتهاء',
    'common.currentTimeSlots': 'فترات الوقت الحالية:',
    'common.currentPackageLimits': 'حدود الحزمة الحالية:',
    'common.noneSet': 'لم يتم التعيين',
    'common.packageName': 'اسم الحزمة',
    'common.min': 'الحد الأدنى',
    'common.max': 'الحد الأقصى',
    'common.daily': 'اليومي',
    
  },
  en: {

    // Navigation
    'nav.home': 'Home',
    'nav.offers': 'Offers',
    'nav.profile': 'Profile',
    'nav.transactions': 'Transactions',
    'nav.withdrawal': 'Withdrawal',
    'nav.login': 'Login',
    'nav.admin': 'Admin Dashboard',
    'nav.logout': 'Logout',
    'nav.deposit': 'Deposit',
    'nav.help': 'Help',
    'nav.team': 'Team',
    'nav.website': 'Website',
    'nav.dashboard': 'Dashboard',
    'nav.register': 'Register',
    
    // Login Page
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your account to access all features',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create account',
    'login.adminLogin': 'Admin Login',
    'login.userLogin': 'User Login',
    'login.success': 'Login successful',
    'login.error': 'Invalid email or password',
    'login.unexpectedError': 'An unexpected error occurred',
    
    // Admin Dashboard
    
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.offers': 'Manage Offers',
    'admin.withdrawals': 'Withdrawal Requests',
    'admin.withdrawals.title': 'Withdrawal Requests',
    'admin.withdrawals.wallet': 'Wallet Type',
    'admin.transactions': 'Transaction Logs',
    'admin.transactions.log': 'Comprehensive log of all platform transactions available for review and export',
    'admin.notifications': 'Notifications',
    'admin.stats.totalUsers': 'Total Users',
    'admin.stats.pendingVerifications': 'Pending Verifications',
    'admin.stats.activeOffers': 'Active Offers',
    'admin.stats.pendingWithdrawals': 'Pending Withdrawals',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.phone': 'Phone',
    'admin.users.status': 'Status',
    'admin.users.verified': 'Verified',
    'admin.users.pending': 'Pending',
    'admin.users.actions': 'Actions',
    'admin.users.verify': 'Verify',
    'admin.users.block': 'Block',
    'admin.users.view': 'View',
    'admin.offers.create': 'Create New Offer',
    'admin.offers.title': 'Offer Title',
    'admin.offers.description': 'Offer Description',
    'admin.offers.type': 'Offer Type',
    'admin.offers.reward': 'Reward',
    'admin.offers.cost': 'Cost',
    'admin.offers.dailyProfit': 'Daily Profit',
    'admin.offers.monthlyProfit': 'Monthly Profit',
    'admin.offers.deadline': 'Deadline',
    'admin.offers.image': 'Offer Image',
    'admin.offers.clickToUpload': 'Click to upload',
    'admin.offers.orDragDrop': 'or drag and drop',
    'admin.offers.imageFormats': 'PNG, JPG, GIF up to 10MB',
    'admin.offers.edit': 'Edit',
    'admin.offers.delete': 'Delete',
    'admin.withdrawals.user': 'User',
    'admin.withdrawals.amount': 'Amount',
    'admin.withdrawals.type': 'Type',
    'admin.withdrawals.method': 'Method',
    'admin.withdrawals.date': 'Date',
    'admin.withdrawals.approve': 'Approve',
    'admin.withdrawals.reject': 'Reject',
    'admin.notifications.send': 'Send Notification',
    'admin.notifications.title': 'Notification Title',
    'admin.notifications.message': 'Message',
    'admin.notifications.type': 'Notification Type',
    'admin.notifications.type.info': 'Info',
    'admin.notifications.type.offer': 'Offer',
    'admin.notifications.type.ad': 'Advertisement',
    'admin.notifications.type.warning': 'Warning',
    'admin.notifications.type.success': 'Success',
    'admin.notifications.type.error': 'Error',
    'admin.notifications.target': 'Target',
    'admin.notifications.target.all': 'All Users',
    'admin.notifications.target.user': 'Specific User',
    'admin.notifications.target.placeholder': 'Enter user ID',
    'admin.notifications.banner': 'Banner Notification',
    'admin.notifications.schedule': 'Schedule Notification',
    'admin.notifications.scheduledAt': 'Scheduled At',
    'admin.notifications.image': 'Image',
    'admin.notifications.status': 'Status',
    'admin.notifications.status.sent': 'Sent',
    'admin.notifications.status.scheduled': 'Scheduled',
    'admin.notifications.actions': 'Actions',
    'admin.notifications.noNotifications': 'No notifications found',
    'admin.notifications.sendToAll': 'Send to All',
    'admin.export.users': 'Export Users',
    'admin.export.transactions': 'Export Transactions',
    'admin.export.title': 'Export Data',
    'admin.export.type': 'Data Type',
    'admin.export.format': 'Export Format',
    'admin.export.selectFormat': 'Select Format',
    'admin.export.export': 'Export',
    'admin.export.exporting': 'Exporting...',
    'admin.export.success': 'Export completed successfully',
    'admin.export.error': 'An error occurred during export',
    'admin.export.pdfSuccess': 'PDF file created successfully',
    'admin.export.pdfReady': 'Print window opened for PDF export',
    'admin.export.excelSuccess': 'Excel file exported successfully',
    'admin.export.excelReady': 'Excel file downloaded successfully',
    'admin.chat': 'Live Support',
    'admin.supportChat': 'Customer Support',
    'admin.chat.searchConversations': 'Search conversations...',
    'admin.chat.selectConversation': 'Select a conversation to view messages',
    
    // Home Page
    'home.title': 'Welcome to Cash',
    'home.subtitle': 'Smart trading platform to manage your earnings securely',
    'home.cta': 'Get Started',
    'home.login': 'Login',
    'home.cta2.title': 'Start Your Journey with Cash Today',
    'home.cta2.subtitle': 'Join thousands of users who trust Cash platform to manage their earnings',
    'home.cta2.button': 'Create Free Account',
    
    // Features
    'features.secure': 'Secure & Safe',
    'features.secure.desc': 'We use the latest security technologies to protect your funds',
    'features.fast': 'Fast & Reliable',
    'features.fast.desc': 'Quick transactions and reliable system for managing your earnings',
    'features.support': '24/7 Support',
    'features.support.desc': 'Our support team is available around the clock to help you',
    
    // Offers Page
    'offers.title': 'Available Offers',
    'offers.subtitle': 'Discover available offers and get additional rewards',
    'offers.trading': 'Trading',
    'offers.referral': 'Referral',
    'offers.premium': 'Premium',
    'offers.deadline': 'Deadline:',
    'offers.minAmount': 'Minimum:',
    'offers.join': 'Join Offer',
    'offers.notification.title': "Don't Miss New Offers!",
    'offers.notification.subtitle': 'Subscribe to notifications to get the latest offers and rewards',
    'offers.notification.button': 'Subscribe to Notifications',
    
    // Profile Page
    'profile.totalEarnings': 'Total Earnings',
    'profile.recentActivity': 'Recent Activity',
    'profile.accountStatus': 'Account Status',
    'profile.emailVerification': 'Email Verification',
    'profile.phoneVerification': 'Phone Verification',
    'profile.identityVerification': 'Identity Verification',
    'profile.accountLevel': 'Account Level',
    'profile.withdrawalStatus': 'Withdrawal Status',
    'profile.withdrawalEligible': 'Your account is eligible for all withdrawals',
    'profile.verified': 'Verified',
    'profile.pending': 'Pending Verification',
    'profile.completed': 'Completed',
    'profile.advanced': 'Advanced',
    'profile.memberSince': 'Member since:',
    'profile.updateAccountInfo': 'Update Account Information',
    'profile.firstName': 'First Name',
    'profile.firstNamePlaceholder': 'Enter first name',
    'profile.lastName': 'Last Name',
    'profile.lastNamePlaceholder': 'Enter last name',
    'profile.phone': 'Phone Number',
    'profile.phonePlaceholder': 'Enter phone number',
    'profile.wallet': 'E-Wallet',
    'profile.selectWallet': 'Select wallet',
    'profile.walletVodafone': 'Vodafone Cash',
    'profile.walletOrange': 'Orange Cash',
    'profile.walletWePay': 'We Pay',
    'profile.walletEtisalat': 'Etisalat Cash',
    'profile.idFront': 'ID Photo - Front',
    'profile.idBack': 'ID Photo - Back',
    'profile.saving': 'Saving...',
    'profile.save': 'Save Data',
    
    // Transactions Page
    'transactions.title': 'Transaction History',
    'transactions.subtitle': 'Track all your financial transactions',
    'transactions.search': 'Search transactions...',
    'transactions.all': 'All Transactions',
    'transactions.withdrawal': 'Withdrawal',
    'transactions.deposit': 'Deposit',
    'transactions.bonus': 'Bonus',
    'transactions.earning': 'Earning',
    'transactions.completed': 'Completed',
    'transactions.approved': 'Approved',
    'transactions.pending': 'Pending',
    'transactions.rejected': 'Rejected',
    'transactions.id': 'Transaction ID:',
    'transactions.noResults': 'No matching transactions',
    'transactions.summary': 'Transaction Summary',
    'transactions.totalIncome': 'Total Income',
    'transactions.totalWithdrawals': 'Total Withdrawals',
    'transactions.pendingCount': 'Pending Transactions',
    
    // Withdrawal Page
    'withdrawal.title': 'Withdrawal Request',
    'withdrawal.subtitle': 'Request withdrawal of your earnings safely and easily',
    'withdrawal.newRequest': 'New Withdrawal Request',
    'withdrawal.type': 'Withdrawal Type',
    'withdrawal.amount': 'Amount',
    'withdrawal.method': 'Withdrawal Method',
    'withdrawal.accountDetails': 'Account Details',
    'withdrawal.maxAmount': 'Maximum:',
    'withdrawal.selectType': 'Select withdrawal type',
    'withdrawal.selectMethod': 'Select withdrawal method',
    'withdrawal.accountPlaceholder': 'Account number or wallet address',
    'withdrawal.submit': 'Submit Withdrawal Request',
    'withdrawal.warning': 'Withdrawal request will be reviewed within 24-48 hours. Make sure account details are correct.',
    'withdrawal.balances': 'Available Balances',
    'withdrawal.verificationStatus': 'Verification Status',
    'withdrawal.eligible': 'Your account is eligible for all withdrawals',
    'withdrawal.verificationRequired': 'Verification Required',
    'withdrawal.verificationMessage': 'Identity verification must be completed before submitting withdrawal requests',
    'withdrawal.completeVerification': 'Complete Verification',
    'withdrawal.bank': 'Bank Transfer',
    'withdrawal.wallet': 'Digital Wallet',
    'withdrawal.crypto': 'Cryptocurrency',
    'withdrawal.error.verification': 'Verification Error',
    'withdrawal.error.verificationMessage': 'Identity verification must be completed before requesting withdrawal',
    'withdrawal.error.amount': 'Amount Error',
    'withdrawal.error.amountMessage': 'Requested amount is greater than available balance',
    'withdrawal.success.message': 'Withdrawal request submitted successfully and will be reviewed soon',
    'withdrawal.error.timeSlot': 'Withdrawal Time Error',
    'withdrawal.error.timeSlotMessage': 'Withdrawals are only allowed during admin-set times',
    'withdrawal.error.limit': 'Limit Error',
    'withdrawal.error.minAmount': 'Amount is less than minimum required (${min})',
    'withdrawal.error.maxAmount': 'Amount exceeds maximum allowed (${max})',
    'withdrawal.error.dailyLimit': 'Daily limit exceeded. Daily limit: ${daily}, Used: ${used}, Remaining: ${remaining}',
    'withdrawal.error.loadData': 'Failed to load withdrawal data',
    'withdrawal.history': 'Withdrawal History',
    'withdrawal.noHistory': 'No withdrawal history',
    'withdrawal.history.id': 'Request ID',
    'withdrawal.history.type': 'Type',
    'withdrawal.history.amount': 'Amount',
    'withdrawal.history.method': 'Method',
    'withdrawal.history.status': 'Status',
    'withdrawal.history.date': 'Date',
    'withdrawal.history.details': 'Details',
    'withdrawal.status.pending': 'Pending',
    'withdrawal.status.approved': 'Approved',
    'withdrawal.status.rejected': 'Rejected',
    'withdrawal.status.paid': 'Paid',
    'withdrawal.rejectionReason': 'Rejection Reason',
    'withdrawal.adminNote': 'Admin Note',
    'withdrawal.packageLimits': 'Package Limits: Min ${min}, Max ${max}, Daily ${daily}',
    'withdrawal.noDetails': 'No additional details',
    
    // Registration
    'register.title': 'Create New Account',
    'register.displayName': 'Display Name',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.referralCode': 'Referral Code (optional)',
    'register.referredBy': 'Referred by',
    'register.checkingReferral': 'Checking referral code...',
    'register.error.invalidReferral': 'Please enter a valid referral code',
    'register.idFront': 'ID Photo - Front',
    'register.idBack': 'ID Photo - Back',
    'register.submit': 'Create Account',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.required': 'All fields are required',
    'register.success': 'Registration request submitted successfully',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'language.switch': 'العربية',
    
    // Deposit Feature
    'deposit.title': 'Deposit Money',
    'deposit.subtitle': 'Send money to one of the official numbers and upload the transfer screenshot',
    'deposit.amount': 'Amount',
    'deposit.userNumber': 'Your sending mobile number',
    'deposit.targetNumber': 'Official deposit number',
    'deposit.upload': 'Upload transfer screenshot',
    'deposit.submit': 'Submit Deposit Request',
    'deposit.success': 'Deposit request submitted successfully and will be reviewed soon',
    'deposit.error.maxNumbers': 'Cannot add more than 10 deposit numbers',
    'deposit.error.required': 'All fields are required',
    'deposit.error.imageType': 'Screenshot must be a jpg or png image',
    'deposit.status.pending': 'Pending',
    'deposit.status.approved': 'Approved',
    'deposit.status.rejected': 'Rejected',
    'deposit.numbers': 'Deposit Numbers',
    'deposit.requests': 'Deposit Requests',
    'deposit.history': 'Deposit History',
    'deposit.screenshot': 'Screenshot',
    'deposit.status': 'Status',
    'deposit.actions': 'Actions',
    'deposit.view': 'View',
    'deposit.date': 'Date',
    'deposit.approve': 'Approve',
    'deposit.reject': 'Reject',
    'deposit.user': 'User',
    
    // Help Center
    'help.title': 'Help Center',
    'help.subtitle': 'Comprehensive guide to all services and features',
    'help.deposit.title': 'How to Deposit',
    'help.deposit.step1': '1. Choose one of the official deposit numbers',
    'help.deposit.step2': '2. Send the required amount to the selected number',
    'help.deposit.step3': '3. Take a screenshot of the transfer or receipt',
    'help.deposit.step4': '4. Fill out the form and attach the screenshot',
    'help.deposit.step5': '5. Wait for request review (24-48 hours)',
    'help.withdrawal.title': 'How to Withdraw',
    'help.withdrawal.step1': '1. Ensure identity verification is completed',
    'help.withdrawal.step2': '2. Select withdrawal type and amount',
    'help.withdrawal.step3': '3. Enter account or wallet details',
    'help.withdrawal.step4': '4. Review information and ensure accuracy',
    'help.withdrawal.step5': '5. Submit request and wait for review',
    'help.invite.title': 'How to Invite Others',
    'help.invite.step1': '1. Go to the offers page',
    'help.invite.step2': '2. Select a referral offer',
    'help.invite.step3': '3. Copy your referral link',
    'help.invite.step4': '4. Share the link with your friends',
    'help.invite.step5': '5. Earn rewards when they join',
    'help.packages.title': 'How Packages Work',
    'help.packages.step1': '1. Browse available packages on the offers page',
    'help.packages.step2': '2. Choose a package that fits your budget',
    'help.packages.step3': '3. Read terms and conditions carefully',
    'help.packages.step4': '4. Pay the required amount',
    'help.packages.step5': '5. Start earning according to the terms',
    'help.faq.title': 'Frequently Asked Questions',
    'help.faq.q1': 'How long does deposit request review take?',
    'help.faq.a1': 'Deposit request review typically takes 24-48 business hours.',
    'help.faq.q2': 'What is the minimum withdrawal amount?',
    'help.faq.a2': 'Minimum withdrawal varies by account type and package.',
    'help.faq.q3': 'How can I check my request status?',
    'help.faq.a3': 'You can track your request status in the transactions page.',
    'help.faq.q4': 'Can I cancel a withdrawal request?',
    'help.faq.a4': 'Withdrawal requests cannot be cancelled after submission, so ensure information accuracy.',
    'help.faq.q5': 'How do I get referral rewards?',
    'help.faq.a5': 'You earn referral rewards when friends join through your link.',
    'help.faq.q6': 'What payment methods are accepted?',
    'help.faq.a6': 'We accept all major Egyptian e-wallets.',
    
    // Chat Support
    'chat.title': 'Live Support',
    'chat.subtitle': 'Connect with our support team for assistance',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send',
    'chat.typing': 'Typing...',
    'chat.online': 'Online',
    'chat.offline': 'Offline',
    'chat.agent': 'Support Agent',
    'chat.user': 'You',
    'chat.welcome': 'Hello! How can I help you today?',
    'chat.quickReplies': 'Quick Replies',
    'chat.quickReply.deposit': 'Deposit Issue',
    'chat.quickReply.withdrawal': 'Withdrawal Issue',
    'chat.quickReply.account': 'Account Issue',
    'chat.quickReply.technical': 'Technical Issue',
    'chat.quickReply.other': 'Other',
    'chat.status.connected': 'Connected',
    'chat.status.connecting': 'Connecting...',
    'chat.status.disconnected': 'Disconnected',
    'chat.error.connection': 'Connection Error',
    'chat.error.message': 'Failed to send message',
    'chat.minimize': 'Minimize',
    'chat.maximize': 'Maximize',
    'chat.close': 'Close',
    'chat.newMessage': 'New Message',
    'chat.noMessages': 'No messages yet',
    'chat.loading': 'Loading...',
    'chat.attachment': 'Attach File',
    'chat.attachment.error': 'File upload error',
    'chat.attachment.size': 'File size too large',
    'chat.attachment.type': 'File type not supported',
    
    // Admin Dashboard Additional
    'admin.analytics': 'Analytics',
    'admin.analytics.newUsersOverTime': 'New Users Over Time',
    'admin.analytics.transactionTypes': 'Transaction Types',
    'admin.analytics.activityByHour': 'Activity By Hour',
    'admin.analytics.newUsers': 'New Users',
    'admin.analytics.date': 'Date',
    'admin.analytics.count': 'Count',
    'admin.analytics.activity': 'Activity',
    'admin.analytics.hour': 'Hour',
    'admin.analytics.chartPlaceholder': 'Charts will be added soon',
    'admin.analytics.approved': 'Approved',
    'admin.analytics.pending': 'Pending',
    'admin.analytics.rejected': 'Rejected',
    'admin.analytics.noData': 'No data available',
    'admin.loading': 'Loading...',
    'admin.noUsers': 'No users found',
    'admin.view': 'View',
    'admin.verify': 'Verify',
    'admin.remove': 'Remove',
    'admin.manageOffers': 'Manage Offers',
    'admin.usersCount': 'Users:',
    'admin.profitLoss': 'Profit/Loss:',
    'admin.proof': 'Proof',
    'admin.confirmPay': 'Confirm Payment',
    'admin.rejectTitle': 'Reject Request',
    'admin.adminNote': 'Admin Note',
    'admin.proofImage': 'Proof Image',
    'admin.rejectionReason': 'Rejection Reason',
    'admin.settings': 'Settings',
    'admin.timeSlots': 'Withdrawal Time Slots',
    'admin.saveTimeSlots': 'Save Time Slots',
    'admin.packageLimits': 'Package Withdrawal Limits',
    'admin.savePackageLimits': 'Save Package Limits',
    'admin.monthlyDeposits': 'Total Deposits This Month',
    'admin.withdrawals.pay': 'Pay',
    'admin.withdrawals.requests': 'requests',
    'admin.withdrawals.noRequests': 'No withdrawal requests',
    'admin.withdrawalSettings': 'Withdrawal Settings',
    'admin.timeSlotsDescription': 'Set allowed withdrawal times (Day:Hour:Minute)',
    'admin.addTimeSlot': 'Add Time Slot',
    'admin.packageLimitsDescription': 'Set withdrawal limits for each package',
    'admin.package': 'Package',
    'admin.minAmount': 'Min Amount',
    'admin.maxAmount': 'Max Amount',
    'admin.dailyLimit': 'Daily Limit',
    'admin.adminNotePlaceholder': 'Add note for user (optional)',
    'admin.clickToUploadProof': 'Click to upload proof image',
    'admin.rejectionReasonPlaceholder': 'Enter rejection reason',
    'admin.rejectionReasonHelp': 'This reason will be sent to the user',
    'admin.withdrawals.paymentConfirmed': 'Payment confirmed successfully',
    'admin.withdrawals.paymentFailed': 'Failed to confirm payment',
    'admin.withdrawals.rejectionConfirmed': 'Request rejected successfully',
    'admin.withdrawals.rejectionFailed': 'Failed to reject request',
    'admin.weeklyNewUsers': 'New Users This Week',
    'admin.avgTransactionValue': 'Average Transaction Value',
    'admin.searchPlaceholder': 'Search by name, email, or phone...',
    'admin.verificationStatus': 'Verification Status',
    'admin.allStatuses': 'All Statuses',
    'admin.verified': 'Verified',
    'admin.pending': 'Pending',
    'admin.registrationDate': 'Registration Date',
    'admin.exportUsers': 'Export Users',
    'admin.exportTransactions': 'Export Transactions',
    'admin.failedToFetch': 'Failed to fetch data',
    'admin.failedToFetchReferrers': 'Failed to fetch top referrers',
    'admin.failedToUpdateSettings': 'Failed to update settings',
    'admin.settingsUpdated': 'Settings updated successfully',
    'admin.referralSettings': 'Referral System Settings',
    'admin.level1Points': 'Level 1 Points (Direct Referrals)',
    'admin.level2Points': 'Level 2 Points (Indirect Referrals)',
    'admin.level3Points': 'Level 3 Points (Third Level)',
    'admin.updateSettings': 'Update Settings',
    'admin.topReferrers': 'Top Referrers',
    'admin.noReferrers': 'No referrers found',
    'admin.referralStats': 'Referral Statistics',
    'admin.totalReferrals': 'Total Referrals',
    'admin.totalPointsAwarded': 'Total Points Awarded',
    'admin.activeReferrers': 'Active Referrers',
    'admin.pts': 'pts',
    'admin.referrals': 'referrals',
    'admin.userVerified': 'User verified successfully',
    'admin.userRemoved': 'User removed successfully',
    'admin.clearFilters': 'Clear Filters',
    'admin.activeFilters': 'Active Filters',
    'admin.noResults': 'No Results',
    'admin.refresh': 'Refresh',
    'admin.details': 'Details',
    'admin.summary': 'Summary',
    'admin.dashboard': 'Dashboard',
    'admin.confirm': 'Confirm',
    'admin.back': 'Back',
    'admin.next': 'Next',
    'admin.previous': 'Previous',
    'admin.first': 'First',
    'admin.last': 'Last',
    'admin.page': 'Page',
    'admin.of': 'of',
    'admin.items': 'items',
    'admin.perPage': 'per page',
    'admin.showing': 'Showing',
    'admin.to': 'to',
    'admin.entries': 'entries',
    
    // Quick Actions
    'admin.quickActions': 'Quick Actions',
    'admin.quickActions.manageOffers': 'Manage Offers',
    'admin.quickActions.exportUsers': 'Export Users',
    'admin.quickActions.exportData': 'Export Data',
    'admin.quickActions.sendNotification': 'Send Notification',
    'admin.quickActions.addDepositNumber': 'Add Deposit Number',
    'admin.quickActions.manageReferrals': 'Manage Referrals',
    'admin.quickActions.viewAnalytics': 'View Analytics',
    'admin.quickActions.manageWithdrawals': 'Manage Withdrawals',
    'admin.quickActions.supportChat': 'Customer Support',
    
    
    // Offers
    'offers.manageOffers': 'Manage Offers',
    'offers.saving': 'Saving...',
    'offers.update': 'Update',
    'offers.create': 'Create',
    'offers.preview': 'Preview',
    'offers.removePreview': 'Remove Preview',
    
    // Deposit
    'deposit.loading': 'Loading deposit page...',
    'deposit.loadingNumber': 'Loading deposit number...',
    'deposit.loginRequired': 'Please login to access the deposit page',
    'deposit.noNumbersAvailable': 'No deposit numbers available',
    'deposit.acceptedFormats': 'Accepted formats: JPEG, PNG. Max size: 5MB',
    'deposit.submitting': 'Submitting...',
    'deposit.error.unexpected': 'An unexpected error occurred. Please try again.',
    
    // Common Additional
    'common.required': 'Required',
    'common.close': 'Close',
    'common.userDetails': 'User Details',
    'common.name': 'Name:',
    'common.email': 'Email:',
    'common.phone': 'Phone:',
    'common.wallet': 'Wallet:',
    'common.verified': 'Verified:',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.now': 'Now',
    'common.minutes': 'min',
    'common.hours': 'hr',
    'common.days': 'day',

    // NotFound Page
    'notfound.404': '404',
    'notfound.oops': 'Oops! Page not found',
    'notfound.returnHome': 'Return to Home',

    // ReferralCode Component
    'referral.program': 'Referral Program',
    'referral.accountVerificationRequired': 'Account Verification Required',
    'referral.verifyToAccess': 'Please verify your account to access the referral program and earn rewards.',
    'referral.loading': 'Loading referral data...',
    'referral.yourProgram': 'Your Referral Program',
    'referral.yourCode': 'Your Referral Code',
    'referral.totalReferrals': 'Total Referrals',
    'referral.pointsEarned': 'Points Earned',
    'referral.level1': 'Level 1',
    'referral.level2plus3': 'Level 2+3',
    'referral.howItWorks': 'How It Works',
    'referral.howItWorks.level1': 'Earn points when friends sign up using your code',
    'referral.howItWorks.level2': 'Earn points when your referrals refer others',
    'referral.howItWorks.level3': 'Earn points from third-level referrals',
    'referral.howItWorks.share': 'Share your code with friends to start earning rewards!',

    // Transactions/General
    'transactions.paymentProcessed': 'Payment processed successfully',
    'transactions.invalidBankDetails': 'Invalid bank account details provided',
    'transactions.friendReferralBonus': 'Friend referral bonus',
    'transactions.personalEarningsWithdrawal': 'Personal earnings withdrawal',
    'transactions.teamEarningsWithdrawal': 'Team earnings withdrawal',
    'transactions.capitalDeposit': 'Capital deposit',
    'transactions.bank': 'Bank',
    'transactions.wallet': 'Wallet',
    'transactions.bankTransfer': 'Bank transfer',
    'transactions.cryptocurrency': 'Cryptocurrency',
    'transactions.teamEarnings': 'Team earnings',
    'common.completeProfile': 'Please complete your account information to access the website. Redirecting to profile setup...',
    'deposit.completeProfile': 'Please complete your account information to make deposits. Redirecting to profile setup...',
    // Help Center Additional
    'help.needMoreHelp': 'Need More Help?',
    'help.supportMessage': 'Our support team is available 24/7 to assist you with any questions or concerns.',
    'help.emailSupport': 'Email Support',
    'help.liveChat': 'Live Chat',
    // Offers Additional
    'offers.joined': 'Joined',
    'offers.cost': 'Cost:',
    'offers.dailyProfit': 'Daily Profit:',
    'offers.monthlyProfit': 'Monthly Profit:',
    'offers.notifyMe': 'Notify Me',
    'offers.stayTuned': 'Stay tuned for the latest offers and rewards.',
    // Transactions Descriptions/Methods
    'transactions.desc.personalEarningsWithdrawal': 'Personal earnings withdrawal',
    'transactions.desc.friendReferralBonus': 'Friend referral bonus',
    'transactions.desc.teamEarnings': 'Team earnings',
    'transactions.desc.bonusWithdrawal': 'Bonus withdrawal',
    'transactions.desc.capitalDeposit': 'Capital deposit',
    'transactions.desc.teamEarningsWithdrawal': 'Team earnings withdrawal',
    'transactions.method.bank': 'Bank',
    'transactions.method.wallet': 'Wallet',
    'transactions.method.bankTransfer': 'Bank transfer',
    'transactions.method.cryptocurrency': 'Cryptocurrency',
    'transactions.approvedForProcessing': 'Approved for processing',
    // Register Page Additional
    'register.invalidReferralTitle': 'Invalid Referral Code',
    'register.invalidReferralDesc': 'The referral code you entered is not valid.',
    'register.unverifiedReferralDesc': 'The referral code belongs to an unverified account.',
    'register.validReferralTitle': 'Valid Referral Code',
    'register.validReferralDesc': "You'll be referred by",
    // Profile Page Additional
    'profile.noData': 'No Profile Data',
    'profile.noDataDesc': 'Please complete your account information to view your profile.',
    'profile.updateAccount': 'Update Account Information',
    'profile.achievements': 'Achievements',
    'profile.level': 'Level',
    'profile.levelDesc': 'Your current level',
    'profile.badges': 'Badges',
    'profile.noBadges': 'No badges earned yet',
    'profile.accountInfo': 'Account Information',
    'profile.edit': 'Edit',
    'profile.idPhotos': 'ID Photos',
    'profile.profilePhoto': 'Profile Photo',
    'profile.view': 'View',
    'profile.idFrontLabel': 'Front',
    'profile.idBackLabel': 'Back',
    'profile.balance': 'Current Balance',
    'profile.personalEarnings': 'Personal Earnings',
    'profile.teamEarnings': 'Team Earnings',
    'profile.bonuses': 'Bonuses',
    'profile.capital': 'Capital',
    // ... existing code ...
    'admin.accept': 'Accept',
    'admin.reject': 'Reject',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'home.hero.title': 'Welcome to Cash',
    'home.hero.subtitle': 'Smart trading platform to manage your earnings securely',
    'home.hero.cta': 'Get Started',
    'home.hero.learnMore': 'Learn More',
    'admin.gamification': 'Gamification',
    'admin.gamificationSettings': 'Gamification Settings',
    'admin.pointsMultiplier': 'Points Multiplier',
    'admin.automation': 'Automation',
    'admin.badges': 'Badges',
    'admin.createBadge': 'Create Badge',
    'admin.editBadge': 'Edit Badge',
    'admin.badgeName': 'Badge Name',
    'admin.badgeDescription': 'Badge Description',
    'admin.badgeType': 'Badge Type',
    'admin.badgeRequirement': 'Badge Requirement',
    'admin.badgePoints': 'Badge Points',
    'admin.badgeActive': 'Badge Active',
    'admin.update': 'Update',
    'admin.create': 'Create',
    'admin.noBadges': 'No badges found',
    'admin.levels': 'Levels',
    'admin.createLevel': 'Create Level',
    'admin.editLevel': 'Edit Level',
    'admin.levelNumber': 'Level Number',
    'admin.levelRequirement': 'Points Required',
    'admin.levelName': 'Level Name',
    'admin.levelDescription': 'Level Description',
    'admin.levelBenefits': 'Level Benefits',
    'admin.noLevels': 'No levels found',
    'admin.userBadges': 'User Badges',
    'admin.assignBadge': 'Assign Badge',
    'admin.editUserBadge': 'Edit User Badge',
    'admin.pointsEarned': 'Points Earned',
    'admin.assign': 'Assign',
    'admin.noUserBadges': 'No user badges found',
    'admin.confirmDelete': 'Confirm Delete',
    'admin.deleteWarning': 'Are you sure you want to delete',
    'admin.deleteWarning2': 'This action cannot be undone.',
    'admin.badgeType.achievement': 'Achievement',
    'admin.badgeType.referral': 'Referral',
    'admin.badgeType.deposit': 'Deposit',
    'admin.badgeType.withdrawal': 'Withdrawal',
    'admin.badgeType.profile': 'Profile',
    'admin.badgeType.verification': 'Verification',
    'admin.badgeType.special': 'Special',
    'admin.badgeType.loyalty': 'Loyalty',
    'admin.automation.enabled': 'Enabled',
    'admin.automation.disabled': 'Disabled',
    'language.arabic': 'Arabic',
    'language.english': 'EN',
    'common.active': 'Active',
    'common.actions': 'Actions',
    'offers.image': 'Image',
    'offers.description': 'Description',
    'offers.amount': 'Amount',
    'offers.noDeadline': 'No deadline',
    'common.day': 'Day',
    'common.day.sunday': 'Sunday',
    'common.day.monday': 'Monday',
    'common.day.tuesday': 'Tuesday',
    'common.day.wednesday': 'Wednesday',
    'common.day.thursday': 'Thursday',
    'common.day.friday': 'Friday',
    'common.day.saturday': 'Saturday',
    'common.startHour': 'Start Hour',
    'common.endHour': 'End Hour',
    'common.currentTimeSlots': 'Current Time Slots:',
    'common.currentPackageLimits': 'Current Package Limits:',
    'common.noneSet': 'None set',
    'common.packageName': 'Package Name',
    'common.min': 'Min',
    'common.max': 'Max',
    'common.daily': 'Daily',

  }
};
