import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations = {
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.offers': 'العروض',
    'nav.profile': 'الملف الشخصي',
    'nav.transactions': 'المعاملات',
    'nav.withdrawal': 'السحب',
    'nav.login': 'تسجيل الدخول',
    'nav.admin': 'لوحة الإدارة',
    'nav.logout': 'تسجيل الخروج',
    'nav.deposit': 'إيداع',
    'nav.help': 'مركز المساعدة',
    
    // Login Page
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'ادخل إلى حسابك للوصول لجميع الميزات',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.submit': 'تسجيل الدخول',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.createAccount': 'إنشاء حساب',
    'login.adminLogin': 'دخول المدير',
    'login.userLogin': 'دخول المستخدم',
    'login.success': 'تم تسجيل الدخول بنجاح',
    'login.error': 'خطأ في البريد الإلكتروني أو كلمة المرور',
    
    // Admin Dashboard
    'admin.title': 'لوحة الإدارة',
    'admin.overview': 'نظرة عامة',
    'admin.users': 'المستخدمون',
    'admin.offers': 'إدارة العروض',
    'admin.withdrawals': 'طلبات السحب',
    'admin.transactions': 'سجل المعاملات',
    'admin.notifications': 'الإشعارات',
    'admin.stats.totalUsers': 'إجمالي المستخدمين',
    'admin.stats.pendingVerifications': 'التحققات المعلقة',
    'admin.stats.activeOffers': 'العروض النشطة',
    'admin.stats.pendingWithdrawals': 'السحوبات المعلقة',
    'admin.users.name': 'الاسم',
    'admin.users.email': 'البريد الإلكتروني',
    'admin.users.phone': 'الهاتف',
    'admin.users.status': 'الحالة',
    'admin.users.verified': 'محقق',
    'admin.users.pending': 'معلق',
    'admin.users.actions': 'الإجراءات',
    'admin.users.verify': 'تحقق',
    'admin.users.block': 'حظر',
    'admin.users.view': 'عرض',
    'admin.offers.create': 'إنشاء عرض جديد',
    'admin.offers.title': 'عنوان العرض',
    'admin.offers.type': 'نوع العرض',
    'admin.offers.reward': 'المكافأة',
    'admin.offers.deadline': 'تاريخ الانتهاء',
    'admin.offers.edit': 'تعديل',
    'admin.offers.delete': 'حذف',
    'admin.withdrawals.user': 'المستخدم',
    'admin.withdrawals.amount': 'المبلغ',
    'admin.withdrawals.type': 'النوع',
    'admin.withdrawals.method': 'الطريقة',
    'admin.withdrawals.date': 'التاريخ',
    'admin.withdrawals.approve': 'موافقة',
    'admin.withdrawals.reject': 'رفض',
    'admin.notifications.send': 'إرسال إشعار',
    'admin.notifications.title': 'عنوان الإشعار',
    'admin.notifications.message': 'الرسالة',
    'admin.notifications.sendToAll': 'إرسال للجميع',
    'admin.export.users': 'تصدير المستخدمين',
    'admin.export.transactions': 'تصدير المعاملات',
    'admin.chat': 'الدعم المباشر',
    
    // Home Page
    'home.title': 'مرحباً بك في كاش',
    'home.subtitle': 'منصة التداول الذكية لإدارة أرباحك بأمان',
    'home.cta': 'ابدأ الآن',
    'home.login': 'تسجيل الدخول',
    'home.cta2.title': 'ابدأ رحلتك مع كاش اليوم',
    'home.cta2.subtitle': 'انضم إلى آلاف المستخدمين الذين يثقون بمنصة كاش لإدارة أرباحهم',
    'home.cta2.button': 'إنشاء حساب مجاني',
    
    // Features
    'features.secure': 'آمن ومضمون',
    'features.secure.desc': 'نحن نستخدم أحدث تقنيات الأمان لحماية أموالك',
    'features.fast': 'سريع وموثوق',
    'features.fast.desc': 'معاملات سريعة ونظام موثوق لإدارة أرباحك',
    'features.support': 'دعم 24/7',
    'features.support.desc': 'فريق الدعم متوفر طوال الوقت لمساعدتك',
    
    // Offers Page
    'offers.title': 'العروض المتاحة',
    'offers.subtitle': 'اكتشف العروض المتاحة واحصل على مكافآت إضافية',
    'offers.trading': 'تداول',
    'offers.referral': 'إحالة',
    'offers.premium': 'متقدم',
    'offers.deadline': 'تاريخ الانتهاء:',
    'offers.minAmount': 'الحد الأدنى:',
    'offers.join': 'الانضمام للعرض',
    'offers.notification.title': 'لا تفوت العروض الجديدة!',
    'offers.notification.subtitle': 'اشترك في الإشعارات للحصول على آخر العروض والمكافآت',
    'offers.notification.button': 'اشترك في الإشعارات',
    
    // Profile Page
    'profile.totalEarnings': 'إجمالي الأرباح',
    'profile.teamEarnings': 'أرباح الفريق',
    'profile.capital': 'رأس المال',
    'profile.personalEarnings': 'الأرباح الشخصية',
    'profile.bonuses': 'المكافآت',
    'profile.recentActivity': 'النشاط الأخير',
    'profile.accountStatus': 'حالة الحساب',
    'profile.emailVerification': 'التحقق من البريد الإلكتروني',
    'profile.phoneVerification': 'التحقق من الهاتف',
    'profile.identityVerification': 'التحقق من الهوية',
    'profile.accountLevel': 'مستوى الحساب',
    'profile.withdrawalStatus': 'حالة السحب',
    'profile.withdrawalEligible': 'حسابك مؤهل لجميع عمليات السحب',
    'profile.verified': 'تم التحقق',
    'profile.pending': 'في انتظار التحقق',
    'profile.completed': 'مكتمل',
    'profile.advanced': 'متقدم',
    'profile.memberSince': 'عضو منذ:',
    'profile.updateAccountInfo': 'تحديث بيانات الحساب',
    'profile.firstName': 'الاسم الأول',
    'profile.firstNamePlaceholder': 'أدخل الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.lastNamePlaceholder': 'أدخل اسم العائلة',
    'profile.phone': 'رقم الهاتف',
    'profile.phonePlaceholder': 'أدخل رقم الهاتف',
    'profile.wallet': 'المحفظة الإلكترونية',
    'profile.selectWallet': 'اختر المحفظة',
    'profile.walletVodafone': 'فودافون كاش',
    'profile.walletOrange': 'أورنج كاش',
    'profile.walletWePay': 'وي باي',
    'profile.walletEtisalat': 'اتصالات كاش',
    'profile.idFront': 'صورة الهوية - الوجه الأمامي',
    'profile.idBack': 'صورة الهوية - الوجه الخلفي',
    'profile.saving': 'جاري الحفظ...',
    'profile.save': 'حفظ البيانات',
    
    // Transactions Page
    'transactions.title': 'سجل المعاملات',
    'transactions.subtitle': 'تتبع جميع معاملاتك المالية',
    'transactions.search': 'البحث في المعاملات...',
    'transactions.all': 'جميع المعاملات',
    'transactions.withdrawal': 'سحب',
    'transactions.deposit': 'إيداع',
    'transactions.bonus': 'مكافأة',
    'transactions.earning': 'أرباح',
    'transactions.completed': 'مكتمل',
    'transactions.pending': 'قيد المعالجة',
    'transactions.rejected': 'مرفوض',
    'transactions.id': 'معرف المعاملة:',
    'transactions.noResults': 'لا توجد معاملات مطابقة',
    'transactions.summary': 'ملخص المعاملات',
    'transactions.totalIncome': 'إجمالي الإيرادات',
    'transactions.totalWithdrawals': 'إجمالي السحوبات',
    'transactions.pendingCount': 'معاملات قيد المعالجة',
    
    // Withdrawal Page
    'withdrawal.title': 'طلب سحب',
    'withdrawal.subtitle': 'اطلب سحب أرباحك بأمان وسهولة',
    'withdrawal.newRequest': 'طلب سحب جديد',
    'withdrawal.type': 'نوع السحب',
    'withdrawal.amount': 'المبلغ',
    'withdrawal.method': 'طريقة السحب',
    'withdrawal.accountDetails': 'تفاصيل الحساب',
    'withdrawal.maxAmount': 'الحد الأقصى:',
    'withdrawal.selectType': 'اختر نوع السحب',
    'withdrawal.selectMethod': 'اختر طريقة السحب',
    'withdrawal.accountPlaceholder': 'رقم الحساب أو عنوان المحفظة',
    'withdrawal.submit': 'تقديم طلب السحب',
    'withdrawal.warning': 'سيتم مراجعة طلب السحب خلال 24-48 ساعة. تأكد من صحة تفاصيل الحساب.',
    'withdrawal.balances': 'الأرصدة المتاحة',
    'withdrawal.verificationStatus': 'حالة التحقق',
    'withdrawal.eligible': 'حسابك مؤهل لجميع عمليات السحب',
    'withdrawal.verificationRequired': 'التحقق مطلوب',
    'withdrawal.verificationMessage': 'يجب إكمال التحقق من الهوية قبل تقديم طلبات السحب',
    'withdrawal.completeVerification': 'إكمال التحقق',
    'withdrawal.bank': 'التحويل البنكي',
    'withdrawal.wallet': 'المحفظة الإلكترونية',
    'withdrawal.crypto': 'العملة المشفرة',
    'withdrawal.error.verification': 'خطأ في التحقق',
    'withdrawal.error.verificationMessage': 'يجب إكمال التحقق من الهوية قبل طلب السحب',
    'withdrawal.error.amount': 'خطأ في المبلغ',
    'withdrawal.error.amountMessage': 'المبلغ المطلوب أكبر من الرصيد المتاح',
    'withdrawal.success.message': 'تم إرسال طلب السحب بنجاح وسيتم مراجعته قريباً',
    
    // Registration
    'register.title': 'إنشاء حساب جديد',
    'register.displayName': 'اسم العرض',
    'register.firstName': 'الاسم الأول',
    'register.lastName': 'اسم العائلة',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.password': 'كلمة المرور',
    'register.referralCode': 'كود الإحالة (اختياري)',
    'register.idFront': 'صورة الهوية - الوجه الأمامي',
    'register.idBack': 'صورة الهوية - الوجه الخلفي',
    'register.submit': 'إنشاء الحساب',
    'register.hasAccount': 'هل لديك حساب بالفعل؟',
    'register.login': 'تسجيل الدخول',
    'register.required': 'جميع الحقول مطلوبة',
    'register.success': 'تم إرسال طلب التسجيل بنجاح',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    
    // Theme
    'theme.light': 'الوضع الفاتح',
    'theme.dark': 'الوضع الداكن',
    'language.switch': 'English',
    
    // Deposit Feature
    'deposit.title': 'إيداع الأموال',
    'deposit.subtitle': 'أرسل الأموال إلى أحد الأرقام الرسمية وأرفق صورة التحويل',
    'deposit.amount': 'المبلغ',
    'deposit.userNumber': 'رقمك المستخدم للإرسال',
    'deposit.targetNumber': 'رقم الإيداع الرسمي',
    'deposit.upload': 'رفع صورة التحويل',
    'deposit.submit': 'إرسال طلب الإيداع',
    'deposit.success': 'تم إرسال طلب الإيداع بنجاح وسيتم مراجعته قريباً',
    'deposit.error.maxNumbers': 'لا يمكن إضافة أكثر من 10 أرقام إيداع',
    'deposit.error.required': 'جميع الحقول مطلوبة',
    'deposit.error.imageType': 'يجب أن تكون الصورة من نوع jpg أو png',
    'deposit.status.pending': 'قيد المراجعة',
    'deposit.status.approved': 'تمت الموافقة',
    'deposit.status.rejected': 'مرفوض',
    'deposit.numbers': 'أرقام الإيداع الرسمية',
    'deposit.requests': 'طلبات الإيداع',
    'deposit.history': 'سجل الإيداعات',
    'deposit.screenshot': 'صورة التحويل',
    'deposit.status': 'الحالة',
    'deposit.actions': 'الإجراءات',
    'deposit.view': 'عرض',
    'deposit.date': 'التاريخ',
    'deposit.approve': 'موافقة',
    'deposit.reject': 'رفض',
    'deposit.user': 'المستخدم',
    
    // Help Center
    'help.title': 'مركز المساعدة',
    'help.subtitle': 'دليل شامل لجميع الخدمات والميزات',
    'help.deposit.title': 'كيفية الإيداع',
    'help.deposit.step1': '1. اختر أحد الأرقام الرسمية للإيداع',
    'help.deposit.step2': '2. أرسل المبلغ المطلوب إلى الرقم المختار',
    'help.deposit.step3': '3. التقط صورة للتحويل أو الإيصال',
    'help.deposit.step4': '4. املأ النموذج وأرفق الصورة',
    'help.deposit.step5': '5. انتظر مراجعة الطلب (24-48 ساعة)',
    'help.withdrawal.title': 'كيفية السحب',
    'help.withdrawal.step1': '1. تأكد من إكمال التحقق من الهوية',
    'help.withdrawal.step2': '2. اختر نوع السحب والمبلغ',
    'help.withdrawal.step3': '3. أدخل تفاصيل الحساب أو المحفظة',
    'help.withdrawal.step4': '4. راجع المعلومات وتأكد من صحتها',
    'help.withdrawal.step5': '5. أرسل الطلب وانتظر المراجعة',
    'help.invite.title': 'كيفية دعوة الآخرين',
    'help.invite.step1': '1. اذهب إلى صفحة العروض',
    'help.invite.step2': '2. اختر عرض الإحالة',
    'help.invite.step3': '3. انسخ رابط الإحالة الخاص بك',
    'help.invite.step4': '4. شارك الرابط مع أصدقائك',
    'help.invite.step5': '5. احصل على مكافآت عند انضمامهم',
    'help.packages.title': 'كيفية عمل الحزم',
    'help.packages.step1': '1. تصفح الحزم المتاحة في صفحة العروض',
    'help.packages.step2': '2. اختر الحزمة المناسبة لميزانيتك',
    'help.packages.step3': '3. اقرأ الشروط والأحكام بعناية',
    'help.packages.step4': '4. ادفع المبلغ المطلوب',
    'help.packages.step5': '5. ابدأ في كسب الأرباح حسب الشروط',
    'help.faq.title': 'الأسئلة الشائعة',
    'help.faq.q1': 'كم تستغرق مراجعة طلب الإيداع؟',
    'help.faq.a1': 'تستغرق مراجعة طلب الإيداع عادة 24-48 ساعة عمل.',
    'help.faq.q2': 'ما هي الحد الأدنى للسحب؟',
    'help.faq.a2': 'الحد الأدنى للسحب يختلف حسب نوع الحساب والحزمة.',
    'help.faq.q3': 'كيف يمكنني التحقق من حالة طلبي؟',
    'help.faq.a3': 'يمكنك تتبع حالة طلبك في صفحة المعاملات.',
    'help.faq.q4': 'هل يمكنني إلغاء طلب السحب؟',
    'help.faq.a4': 'لا يمكن إلغاء طلب السحب بعد إرساله، لذا تأكد من صحة المعلومات.',
    'help.faq.q5': 'كيف أحصل على مكافآت الإحالة؟',
    'help.faq.a5': 'تحصل على مكافآت الإحالة عند انضمام أصدقائك عبر رابطك.',
    'help.faq.q6': 'ما هي طرق الدفع المقبولة؟',
    'help.faq.a6': 'نقبل جميع المحافظ الإلكترونية الرئيسية في مصر.',
    
    // Chat Support
    'chat.title': 'الدعم المباشر',
    'chat.subtitle': 'تواصل مع فريق الدعم للحصول على المساعدة',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.send': 'إرسال',
    'chat.typing': 'جاري الكتابة...',
    'chat.online': 'متصل',
    'chat.offline': 'غير متصل',
    'chat.agent': 'ممثل الدعم',
    'chat.user': 'أنت',
    'chat.welcome': 'مرحباً! كيف يمكنني مساعدتك اليوم؟',
    'chat.quickReplies': 'ردود سريعة',
    'chat.quickReply.deposit': 'مشكلة في الإيداع',
    'chat.quickReply.withdrawal': 'مشكلة في السحب',
    'chat.quickReply.account': 'مشكلة في الحساب',
    'chat.quickReply.technical': 'مشكلة تقنية',
    'chat.quickReply.other': 'أخرى',
    'chat.status.connected': 'متصل',
    'chat.status.connecting': 'جاري الاتصال...',
    'chat.status.disconnected': 'غير متصل',
    'chat.error.connection': 'خطأ في الاتصال',
    'chat.error.message': 'فشل في إرسال الرسالة',
    'chat.minimize': 'تصغير',
    'chat.maximize': 'تكبير',
    'chat.close': 'إغلاق',
    'chat.newMessage': 'رسالة جديدة',
    'chat.noMessages': 'لا توجد رسائل بعد',
    'chat.loading': 'جاري التحميل...',
    'chat.attachment': 'إرفاق ملف',
    'chat.attachment.error': 'خطأ في رفع الملف',
    'chat.attachment.size': 'حجم الملف كبير جداً',
    'chat.attachment.type': 'نوع الملف غير مدعوم',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.offers': 'Offers',
    'nav.profile': 'Profile',
    'nav.transactions': 'Transactions',
    'nav.withdrawal': 'Withdrawal',
    'nav.login': 'Login',
    'nav.admin': 'Admin Dashboard',
    'nav.logout': 'Logout',
    'nav.deposit': 'Deposit',
    'nav.help': 'Help Center',
    
    // Login Page
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your account to access all features',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create account',
    'login.adminLogin': 'Admin Login',
    'login.userLogin': 'User Login',
    'login.success': 'Login successful',
    'login.error': 'Invalid email or password',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.offers': 'Manage Offers',
    'admin.withdrawals': 'Withdrawal Requests',
    'admin.transactions': 'Transaction Logs',
    'admin.notifications': 'Notifications',
    'admin.stats.totalUsers': 'Total Users',
    'admin.stats.pendingVerifications': 'Pending Verifications',
    'admin.stats.activeOffers': 'Active Offers',
    'admin.stats.pendingWithdrawals': 'Pending Withdrawals',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.phone': 'Phone',
    'admin.users.status': 'Status',
    'admin.users.verified': 'Verified',
    'admin.users.pending': 'Pending',
    'admin.users.actions': 'Actions',
    'admin.users.verify': 'Verify',
    'admin.users.block': 'Block',
    'admin.users.view': 'View',
    'admin.offers.create': 'Create New Offer',
    'admin.offers.title': 'Offer Title',
    'admin.offers.type': 'Offer Type',
    'admin.offers.reward': 'Reward',
    'admin.offers.deadline': 'Deadline',
    'admin.offers.edit': 'Edit',
    'admin.offers.delete': 'Delete',
    'admin.withdrawals.user': 'User',
    'admin.withdrawals.amount': 'Amount',
    'admin.withdrawals.type': 'Type',
    'admin.withdrawals.method': 'Method',
    'admin.withdrawals.date': 'Date',
    'admin.withdrawals.approve': 'Approve',
    'admin.withdrawals.reject': 'Reject',
    'admin.notifications.send': 'Send Notification',
    'admin.notifications.title': 'Notification Title',
    'admin.notifications.message': 'Message',
    'admin.notifications.sendToAll': 'Send to All',
    'admin.export.users': 'Export Users',
    'admin.export.transactions': 'Export Transactions',
    'admin.chat': 'Live Support',
    
    // Home Page
    'home.title': 'Welcome to Cash',
    'home.subtitle': 'Smart trading platform to manage your earnings securely',
    'home.cta': 'Get Started',
    'home.login': 'Login',
    'home.cta2.title': 'Start Your Journey with Cash Today',
    'home.cta2.subtitle': 'Join thousands of users who trust Cash platform to manage their earnings',
    'home.cta2.button': 'Create Free Account',
    
    // Features
    'features.secure': 'Secure & Safe',
    'features.secure.desc': 'We use the latest security technologies to protect your funds',
    'features.fast': 'Fast & Reliable',
    'features.fast.desc': 'Quick transactions and reliable system for managing your earnings',
    'features.support': '24/7 Support',
    'features.support.desc': 'Our support team is available around the clock to help you',
    
    // Offers Page
    'offers.title': 'Available Offers',
    'offers.subtitle': 'Discover available offers and get additional rewards',
    'offers.trading': 'Trading',
    'offers.referral': 'Referral',
    'offers.premium': 'Premium',
    'offers.deadline': 'Deadline:',
    'offers.minAmount': 'Minimum:',
    'offers.join': 'Join Offer',
    'offers.notification.title': "Don't Miss New Offers!",
    'offers.notification.subtitle': 'Subscribe to notifications to get the latest offers and rewards',
    'offers.notification.button': 'Subscribe to Notifications',
    
    // Profile Page
    'profile.totalEarnings': 'Total Earnings',
    'profile.teamEarnings': 'Team Earnings',
    'profile.capital': 'Capital',
    'profile.personalEarnings': 'Personal Earnings',
    'profile.bonuses': 'Bonuses',
    'profile.recentActivity': 'Recent Activity',
    'profile.accountStatus': 'Account Status',
    'profile.emailVerification': 'Email Verification',
    'profile.phoneVerification': 'Phone Verification',
    'profile.identityVerification': 'Identity Verification',
    'profile.accountLevel': 'Account Level',
    'profile.withdrawalStatus': 'Withdrawal Status',
    'profile.withdrawalEligible': 'Your account is eligible for all withdrawals',
    'profile.verified': 'Verified',
    'profile.pending': 'Pending Verification',
    'profile.completed': 'Completed',
    'profile.advanced': 'Advanced',
    'profile.memberSince': 'Member since:',
    'profile.updateAccountInfo': 'Update Account Information',
    'profile.firstName': 'First Name',
    'profile.firstNamePlaceholder': 'Enter first name',
    'profile.lastName': 'Last Name',
    'profile.lastNamePlaceholder': 'Enter last name',
    'profile.phone': 'Phone Number',
    'profile.phonePlaceholder': 'Enter phone number',
    'profile.wallet': 'E-Wallet',
    'profile.selectWallet': 'Select wallet',
    'profile.walletVodafone': 'Vodafone Cash',
    'profile.walletOrange': 'Orange Cash',
    'profile.walletWePay': 'We Pay',
    'profile.walletEtisalat': 'Etisalat Cash',
    'profile.idFront': 'ID Photo - Front',
    'profile.idBack': 'ID Photo - Back',
    'profile.saving': 'Saving...',
    'profile.save': 'Save Data',
    
    // Transactions Page
    'transactions.title': 'Transaction History',
    'transactions.subtitle': 'Track all your financial transactions',
    'transactions.search': 'Search transactions...',
    'transactions.all': 'All Transactions',
    'transactions.withdrawal': 'Withdrawal',
    'transactions.deposit': 'Deposit',
    'transactions.bonus': 'Bonus',
    'transactions.earning': 'Earning',
    'transactions.completed': 'Completed',
    'transactions.pending': 'Pending',
    'transactions.rejected': 'Rejected',
    'transactions.id': 'Transaction ID:',
    'transactions.noResults': 'No matching transactions',
    'transactions.summary': 'Transaction Summary',
    'transactions.totalIncome': 'Total Income',
    'transactions.totalWithdrawals': 'Total Withdrawals',
    'transactions.pendingCount': 'Pending Transactions',
    
    // Withdrawal Page
    'withdrawal.title': 'Withdrawal Request',
    'withdrawal.subtitle': 'Request withdrawal of your earnings safely and easily',
    'withdrawal.newRequest': 'New Withdrawal Request',
    'withdrawal.type': 'Withdrawal Type',
    'withdrawal.amount': 'Amount',
    'withdrawal.method': 'Withdrawal Method',
    'withdrawal.accountDetails': 'Account Details',
    'withdrawal.maxAmount': 'Maximum:',
    'withdrawal.selectType': 'Select withdrawal type',
    'withdrawal.selectMethod': 'Select withdrawal method',
    'withdrawal.accountPlaceholder': 'Account number or wallet address',
    'withdrawal.submit': 'Submit Withdrawal Request',
    'withdrawal.warning': 'Withdrawal request will be reviewed within 24-48 hours. Make sure account details are correct.',
    'withdrawal.balances': 'Available Balances',
    'withdrawal.verificationStatus': 'Verification Status',
    'withdrawal.eligible': 'Your account is eligible for all withdrawals',
    'withdrawal.verificationRequired': 'Verification Required',
    'withdrawal.verificationMessage': 'Identity verification must be completed before submitting withdrawal requests',
    'withdrawal.completeVerification': 'Complete Verification',
    'withdrawal.bank': 'Bank Transfer',
    'withdrawal.wallet': 'Digital Wallet',
    'withdrawal.crypto': 'Cryptocurrency',
    'withdrawal.error.verification': 'Verification Error',
    'withdrawal.error.verificationMessage': 'Identity verification must be completed before requesting withdrawal',
    'withdrawal.error.amount': 'Amount Error',
    'withdrawal.error.amountMessage': 'Requested amount is greater than available balance',
    'withdrawal.success.message': 'Withdrawal request submitted successfully and will be reviewed soon',
    
    // Registration
    'register.title': 'Create New Account',
    'register.displayName': 'Display Name',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.referralCode': 'Referral Code (optional)',
    'register.idFront': 'ID Photo - Front',
    'register.idBack': 'ID Photo - Back',
    'register.submit': 'Create Account',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.required': 'All fields are required',
    'register.success': 'Registration request submitted successfully',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'language.switch': 'العربية',
    
    // Deposit Feature
    'deposit.title': 'Deposit Money',
    'deposit.subtitle': 'Send money to one of the official numbers and upload the transfer screenshot',
    'deposit.amount': 'Amount',
    'deposit.userNumber': 'Your sending mobile number',
    'deposit.targetNumber': 'Official deposit number',
    'deposit.upload': 'Upload transfer screenshot',
    'deposit.submit': 'Submit Deposit Request',
    'deposit.success': 'Deposit request submitted successfully and will be reviewed soon',
    'deposit.error.maxNumbers': 'Cannot add more than 10 deposit numbers',
    'deposit.error.required': 'All fields are required',
    'deposit.error.imageType': 'Screenshot must be a jpg or png image',
    'deposit.status.pending': 'Pending',
    'deposit.status.approved': 'Approved',
    'deposit.status.rejected': 'Rejected',
    'deposit.numbers': 'Deposit Numbers',
    'deposit.requests': 'Deposit Requests',
    'deposit.history': 'Deposit History',
    'deposit.screenshot': 'Screenshot',
    'deposit.status': 'Status',
    'deposit.actions': 'Actions',
    'deposit.view': 'View',
    'deposit.date': 'Date',
    'deposit.approve': 'Approve',
    'deposit.reject': 'Reject',
    'deposit.user': 'User',
    
    // Help Center
    'help.title': 'Help Center',
    'help.subtitle': 'Comprehensive guide to all services and features',
    'help.deposit.title': 'How to Deposit',
    'help.deposit.step1': '1. Choose one of the official deposit numbers',
    'help.deposit.step2': '2. Send the required amount to the selected number',
    'help.deposit.step3': '3. Take a screenshot of the transfer or receipt',
    'help.deposit.step4': '4. Fill out the form and attach the screenshot',
    'help.deposit.step5': '5. Wait for request review (24-48 hours)',
    'help.withdrawal.title': 'How to Withdraw',
    'help.withdrawal.step1': '1. Ensure identity verification is completed',
    'help.withdrawal.step2': '2. Select withdrawal type and amount',
    'help.withdrawal.step3': '3. Enter account or wallet details',
    'help.withdrawal.step4': '4. Review information and ensure accuracy',
    'help.withdrawal.step5': '5. Submit request and wait for review',
    'help.invite.title': 'How to Invite Others',
    'help.invite.step1': '1. Go to the offers page',
    'help.invite.step2': '2. Select a referral offer',
    'help.invite.step3': '3. Copy your referral link',
    'help.invite.step4': '4. Share the link with your friends',
    'help.invite.step5': '5. Earn rewards when they join',
    'help.packages.title': 'How Packages Work',
    'help.packages.step1': '1. Browse available packages on the offers page',
    'help.packages.step2': '2. Choose a package that fits your budget',
    'help.packages.step3': '3. Read terms and conditions carefully',
    'help.packages.step4': '4. Pay the required amount',
    'help.packages.step5': '5. Start earning according to the terms',
    'help.faq.title': 'Frequently Asked Questions',
    'help.faq.q1': 'How long does deposit request review take?',
    'help.faq.a1': 'Deposit request review typically takes 24-48 business hours.',
    'help.faq.q2': 'What is the minimum withdrawal amount?',
    'help.faq.a2': 'Minimum withdrawal varies by account type and package.',
    'help.faq.q3': 'How can I check my request status?',
    'help.faq.a3': 'You can track your request status in the transactions page.',
    'help.faq.q4': 'Can I cancel a withdrawal request?',
    'help.faq.a4': 'Withdrawal requests cannot be cancelled after submission, so ensure information accuracy.',
    'help.faq.q5': 'How do I get referral rewards?',
    'help.faq.a5': 'You earn referral rewards when friends join through your link.',
    'help.faq.q6': 'What payment methods are accepted?',
    'help.faq.a6': 'We accept all major Egyptian e-wallets.',
    
    // Chat Support
    'chat.title': 'Live Support',
    'chat.subtitle': 'Connect with our support team for assistance',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send',
    'chat.typing': 'Typing...',
    'chat.online': 'Online',
    'chat.offline': 'Offline',
    'chat.agent': 'Support Agent',
    'chat.user': 'You',
    'chat.welcome': 'Hello! How can I help you today?',
    'chat.quickReplies': 'Quick Replies',
    'chat.quickReply.deposit': 'Deposit Issue',
    'chat.quickReply.withdrawal': 'Withdrawal Issue',
    'chat.quickReply.account': 'Account Issue',
    'chat.quickReply.technical': 'Technical Issue',
    'chat.quickReply.other': 'Other',
    'chat.status.connected': 'Connected',
    'chat.status.connecting': 'Connecting...',
    'chat.status.disconnected': 'Disconnected',
    'chat.error.connection': 'Connection Error',
    'chat.error.message': 'Failed to send message',
    'chat.minimize': 'Minimize',
    'chat.maximize': 'Maximize',
    'chat.close': 'Close',
    'chat.newMessage': 'New Message',
    'chat.noMessages': 'No messages yet',
    'chat.loading': 'Loading...',
    'chat.attachment': 'Attach File',
    'chat.attachment.error': 'File upload error',
    'chat.attachment.size': 'File size too large',
    'chat.attachment.type': 'File type not supported',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar'); // Default to Arabic
  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  useEffect(() => {
    // Apply direction to document
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    
    // Apply font class based on language
    document.body.className = document.body.className.replace(/font-(arabic|english)/, '');
    document.body.classList.add(language === 'ar' ? 'font-arabic' : 'font-english');
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
